// AUTOGENERADO por scripts/gen_ui.mjs — NO editar a mano.
export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  "pt": {
    "proc_title": "A preparar a sua transcrição…",
    "proc_sub": "Estamos a processar o seu áudio para maior precisão.",
    "err": "Não foi possível transcrever. Experimente outro ficheiro ou tente novamente.",
    "missing": "Falta-lhe {x} da transcrição",
    "unlock_title": "Desbloquear a transcrição",
    "pitch": "Isto é apenas o início. Desbloqueie a transcrição completa, edite-a e transfira-a em TXT, DOCX, PDF e SRT.",
    "cta": "Desbloquear agora — {today}",
    "cta_sub": "{today} nos primeiros {n} dias, depois {price}/mês · Cancele quando quiser.",
    "expired": "O ficheiro original expirou e foi eliminado. Após subscrever, carregue-o novamente para concluir a transcrição.",
    "sec_edit": "Editar",
    "sec_export": "Exportar",
    "sec_more": "Mais",
    "it_search": "Localizar e substituir",
    "it_save": "Guardar alterações",
    "it_pdf": "Transferir PDF",
    "it_docx": "Transferir DOCX",
    "it_txt": "Transferir TXT",
    "it_srt": "Transferir SRT",
    "it_ts": "Mostrar marcas de tempo",
    "it_translate": "Traduzir",
    "it_share": "Partilhar transcrição",
    "it_audio": "Transferir áudio",
    "it_rename": "Mudar o nome do ficheiro",
    "it_move": "Mover",
    "it_delete": "Eliminar ficheiro",
    "item_locked": "Desbloqueie para usar esta opção",
    "pay_today": "A pagar hoje",
    "pay_desc": "{n} dias de acesso total. Depois {price}/mês. Cancele quando quiser.",
    "email": "Email",
    "loading_pay": "A carregar pagamento seguro…",
    "processing": "A processar…",
    "legal_pre": "Ao continuar, concorda com os nossos",
    "legal_terms": "Termos",
    "legal_sub": "Subscrição e reembolsos",
    "legal_privacy": "Privacidade",
    "pay_secure": "Pagamento seguro com Stripe.",
    "email_invalid": "Introduza um email válido.",
    "pay_error": "Não foi possível processar o pagamento."
  },
  "fr": {
    "proc_title": "Préparation de votre transcription…",
    "proc_sub": "Nous traitons votre audio pour plus de précision.",
    "err": "La transcription a échoué. Essayez un autre fichier ou réessayez.",
    "missing": "Il vous manque {x} de la transcription",
    "unlock_title": "Débloquer la transcription",
    "pitch": "Ce n'est que le début. Débloquez la transcription complète, modifiez-la et téléchargez-la en TXT, DOCX, PDF et SRT.",
    "cta": "Débloquer maintenant — {today}",
    "cta_sub": "{today} pendant les {n} premiers jours, puis {price}/mois · Annulable à tout moment.",
    "expired": "Le fichier d'origine a expiré et a été supprimé. Après votre abonnement, importez-le à nouveau pour terminer la transcription.",
    "sec_edit": "Modifier",
    "sec_export": "Exporter",
    "sec_more": "Plus",
    "it_search": "Rechercher et remplacer",
    "it_save": "Enregistrer les modifications",
    "it_pdf": "Télécharger en PDF",
    "it_docx": "Télécharger en DOCX",
    "it_txt": "Télécharger en TXT",
    "it_srt": "Télécharger en SRT",
    "it_ts": "Afficher les horodatages",
    "it_translate": "Traduire",
    "it_share": "Partager la transcription",
    "it_audio": "Télécharger l'audio",
    "it_rename": "Renommer le fichier",
    "it_move": "Déplacer",
    "it_delete": "Supprimer le fichier",
    "item_locked": "Débloquez pour utiliser cette option",
    "pay_today": "À payer aujourd'hui",
    "pay_desc": "{n} jours d'accès complet. Puis {price}/mois. Annulable à tout moment.",
    "email": "E-mail",
    "loading_pay": "Chargement du paiement sécurisé…",
    "processing": "Traitement…",
    "legal_pre": "En continuant, vous acceptez nos",
    "legal_terms": "Conditions",
    "legal_sub": "Abonnement et remboursements",
    "legal_privacy": "Confidentialité",
    "pay_secure": "Paiement sécurisé avec Stripe.",
    "email_invalid": "Saisissez une adresse e-mail valide.",
    "pay_error": "Le paiement n'a pas pu être traité."
  },
  "de": {
    "proc_title": "Transkription wird vorbereitet…",
    "proc_sub": "Wir verarbeiten dein Audio für höchste Genauigkeit.",
    "err": "Transkription fehlgeschlagen. Versuche eine andere Datei oder versuche es erneut.",
    "missing": "Dir fehlen {x} der Transkription",
    "unlock_title": "Transkription freischalten",
    "pitch": "Das ist erst der Anfang. Schalte die vollständige Transkription frei, bearbeite sie und lade sie als TXT, DOCX, PDF und SRT herunter.",
    "cta": "Jetzt freischalten — {today}",
    "cta_sub": "{today} für die ersten {n} Tage, danach {price}/Monat · Jederzeit kündbar.",
    "expired": "Die Originaldatei ist abgelaufen und wurde gelöscht. Lade sie nach dem Abschluss des Abos erneut hoch, um die Transkription abzuschließen.",
    "sec_edit": "Bearbeiten",
    "sec_export": "Exportieren",
    "sec_more": "Mehr",
    "it_search": "Suchen und ersetzen",
    "it_save": "Änderungen speichern",
    "it_pdf": "PDF herunterladen",
    "it_docx": "DOCX herunterladen",
    "it_txt": "TXT herunterladen",
    "it_srt": "SRT herunterladen",
    "it_ts": "Zeitstempel anzeigen",
    "it_translate": "Übersetzen",
    "it_share": "Transkription teilen",
    "it_audio": "Audio herunterladen",
    "it_rename": "Datei umbenennen",
    "it_move": "Verschieben",
    "it_delete": "Datei löschen",
    "item_locked": "Freischalten, um diese Option zu nutzen",
    "pay_today": "Heute fällig",
    "pay_desc": "{n} Tage voller Zugriff. Danach {price}/Monat. Jederzeit kündbar.",
    "email": "E-Mail",
    "loading_pay": "Sichere Zahlung wird geladen…",
    "processing": "Wird verarbeitet…",
    "legal_pre": "Wenn du fortfährst, akzeptierst du unsere",
    "legal_terms": "AGB",
    "legal_sub": "Abo & Rückerstattungen",
    "legal_privacy": "Datenschutz",
    "pay_secure": "Sichere Zahlung mit Stripe.",
    "email_invalid": "Gib eine gültige E-Mail-Adresse ein.",
    "pay_error": "Zahlung konnte nicht verarbeitet werden."
  },
  "it": {
    "proc_title": "Preparazione della trascrizione…",
    "proc_sub": "Stiamo elaborando il tuo audio per garantire la precisione.",
    "err": "Non siamo riusciti a trascriverlo. Prova con un altro file o riprova.",
    "missing": "Ti manca {x} di trascrizione",
    "unlock_title": "Sblocca la trascrizione",
    "pitch": "Questo è solo l'inizio. Sblocca la trascrizione completa, modificala e scaricala in TXT, DOCX, PDF e SRT.",
    "cta": "Sblocca ora — {today}",
    "cta_sub": "{today} per i primi {n} giorni, poi {price}/mese · Disdici quando vuoi.",
    "expired": "Il file originale è scaduto ed è stato eliminato. Dopo l'abbonamento, caricalo di nuovo per completare la trascrizione.",
    "sec_edit": "Modifica",
    "sec_export": "Esporta",
    "sec_more": "Altro",
    "it_search": "Trova e sostituisci",
    "it_save": "Salva le modifiche",
    "it_pdf": "Scarica PDF",
    "it_docx": "Scarica DOCX",
    "it_txt": "Scarica TXT",
    "it_srt": "Scarica SRT",
    "it_ts": "Mostra timestamp",
    "it_translate": "Traduci",
    "it_share": "Condividi trascrizione",
    "it_audio": "Scarica audio",
    "it_rename": "Rinomina file",
    "it_move": "Sposta",
    "it_delete": "Elimina file",
    "item_locked": "Sblocca per usare questa opzione",
    "pay_today": "Da pagare oggi",
    "pay_desc": "{n} giorni di accesso completo. Poi {price}/mese. Disdici quando vuoi.",
    "email": "Email",
    "loading_pay": "Caricamento del pagamento sicuro…",
    "processing": "Elaborazione…",
    "legal_pre": "Continuando accetti i nostri",
    "legal_terms": "Termini",
    "legal_sub": "Abbonamento e rimborsi",
    "legal_privacy": "Privacy",
    "pay_secure": "Pagamento sicuro con Stripe.",
    "email_invalid": "Inserisci un'email valida.",
    "pay_error": "Impossibile elaborare il pagamento."
  },
  "nl": {
    "proc_title": "Je transcriptie wordt voorbereid…",
    "proc_sub": "We verwerken je audio voor de nauwkeurigheid.",
    "err": "We konden het niet transcriberen. Probeer een ander bestand of probeer het opnieuw.",
    "missing": "Je mist {x} van de transcriptie",
    "unlock_title": "Ontgrendel de transcriptie",
    "pitch": "Dit is nog maar het begin. Ontgrendel de volledige transcriptie, bewerk deze en download deze als TXT, DOCX, PDF en SRT.",
    "cta": "Nu ontgrendelen — {today}",
    "cta_sub": "{today} voor de eerste {n} dagen, daarna {price}/mnd · Altijd opzegbaar.",
    "expired": "Het originele bestand is verlopen en verwijderd. Upload het na je abonnement opnieuw om de transcriptie te voltooien.",
    "sec_edit": "Bewerken",
    "sec_export": "Exporteren",
    "sec_more": "Meer",
    "it_search": "Zoeken en vervangen",
    "it_save": "Wijzigingen opslaan",
    "it_pdf": "PDF downloaden",
    "it_docx": "DOCX downloaden",
    "it_txt": "TXT downloaden",
    "it_srt": "SRT downloaden",
    "it_ts": "Tijdstempels tonen",
    "it_translate": "Vertalen",
    "it_share": "Transcriptie delen",
    "it_audio": "Audio downloaden",
    "it_rename": "Bestand hernoemen",
    "it_move": "Verplaatsen",
    "it_delete": "Bestand verwijderen",
    "item_locked": "Ontgrendel om deze optie te gebruiken",
    "pay_today": "Vandaag te betalen",
    "pay_desc": "{n} dagen volledige toegang. Daarna {price}/mnd. Altijd opzegbaar.",
    "email": "E-mail",
    "loading_pay": "Beveiligde betaling laden…",
    "processing": "Verwerken…",
    "legal_pre": "Door verder te gaan ga je akkoord met onze",
    "legal_terms": "Voorwaarden",
    "legal_sub": "Abonnement & terugbetalingen",
    "legal_privacy": "Privacy",
    "pay_secure": "Veilig betalen met Stripe.",
    "email_invalid": "Voer een geldig e-mailadres in.",
    "pay_error": "De betaling kon niet worden verwerkt."
  },
  "pl": {
    "proc_title": "Przygotowujemy transkrypcję…",
    "proc_sub": "Przetwarzamy Twoje audio, aby zapewnić dokładność.",
    "err": "Nie udało się utworzyć transkrypcji. Spróbuj z innym plikiem lub spróbuj ponownie.",
    "missing": "Brakuje Ci {x} transkrypcji",
    "unlock_title": "Odblokuj transkrypcję",
    "pitch": "To dopiero początek. Odblokuj pełną transkrypcję, edytuj ją i pobierz w formatach TXT, DOCX, PDF i SRT.",
    "cta": "Odblokuj teraz — {today}",
    "cta_sub": "{today} przez pierwsze {n} dni, potem {price}/mies. · Anuluj w każdej chwili.",
    "expired": "Oryginalny plik wygasł i został usunięty. Po wykupieniu subskrypcji prześlij go ponownie, aby dokończyć transkrypcję.",
    "sec_edit": "Edycja",
    "sec_export": "Eksport",
    "sec_more": "Więcej",
    "it_search": "Znajdź i zamień",
    "it_save": "Zapisz zmiany",
    "it_pdf": "Pobierz PDF",
    "it_docx": "Pobierz DOCX",
    "it_txt": "Pobierz TXT",
    "it_srt": "Pobierz SRT",
    "it_ts": "Pokaż znaczniki czasu",
    "it_translate": "Przetłumacz",
    "it_share": "Udostępnij transkrypcję",
    "it_audio": "Pobierz audio",
    "it_rename": "Zmień nazwę pliku",
    "it_move": "Przenieś",
    "it_delete": "Usuń plik",
    "item_locked": "Odblokuj, aby użyć tej opcji",
    "pay_today": "Do zapłaty dziś",
    "pay_desc": "{n} dni pełnego dostępu. Potem {price}/mies. Anuluj w każdej chwili.",
    "email": "E-mail",
    "loading_pay": "Ładowanie bezpiecznej płatności…",
    "processing": "Przetwarzanie…",
    "legal_pre": "Kontynuując, akceptujesz nasze",
    "legal_terms": "Warunki",
    "legal_sub": "Subskrypcja i zwroty",
    "legal_privacy": "Prywatność",
    "pay_secure": "Bezpieczna płatność przez Stripe.",
    "email_invalid": "Podaj prawidłowy adres e-mail.",
    "pay_error": "Nie udało się przetworzyć płatności."
  }
};
