// AUTOGENERADO por scripts/gen_ui.mjs + scripts/merge_ui.mjs — NO editar a mano (añade JSON en scripts/ui-translations/).
export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  "pt": {
    "proc_title": "A preparar a sua transcrição…",
    "proc_sub": "Estamos a processar o seu áudio para maior precisão.",
    "err": "Não foi possível transcrever. Experimente outro ficheiro ou tente novamente.",
    "missing": "Falta-lhe {x} da transcrição",
    "unlock_title": "Desbloquear a transcrição",
    "pitch": "Isto é apenas o início. Desbloqueie a transcrição completa, edite-a e exporte-a em TXT, DOCX, PDF e SRT.",
    "cta": "Desbloquear agora — {today}",
    "cta_sub": "{today} nos primeiros {n} dias, depois {price}/mês · Cancele quando quiser.",
    "expired": "O ficheiro original expirou e foi eliminado. Depois de subscrever, carregue-o novamente para concluir a transcrição.",
    "sec_edit": "Editar",
    "sec_export": "Exportar",
    "sec_more": "Mais",
    "it_search": "Localizar e substituir",
    "it_save": "Guardar alterações",
    "it_pdf": "Transferir PDF",
    "it_docx": "Transferir DOCX",
    "it_txt": "Transferir TXT",
    "it_srt": "Transferir SRT",
    "it_ts": "Mostrar marcas de tempo",
    "it_translate": "Traduzir",
    "it_share": "Partilhar transcrição",
    "it_audio": "Transferir áudio",
    "it_rename": "Mudar o nome do ficheiro",
    "it_move": "Mover",
    "it_delete": "Eliminar ficheiro",
    "item_locked": "Desbloqueie para usar esta opção",
    "pay_today": "A pagar hoje",
    "pay_desc": "{n} dias de acesso total. Depois {price}/mês. Cancele quando quiser.",
    "email": "Email",
    "loading_pay": "A carregar pagamento seguro…",
    "processing": "A processar…",
    "legal_pre": "Ao continuar, concorda com os nossos",
    "legal_terms": "Termos",
    "legal_sub": "Subscrição e reembolsos",
    "legal_privacy": "Privacidade",
    "pay_secure": "Pagamento seguro com Stripe.",
    "email_invalid": "Introduza um email válido.",
    "pay_error": "Não foi possível processar o pagamento.",
    "reupload_title": "Carregue o seu ficheiro completo",
    "reupload_desc": "A sua subscrição está ativa. Como o ficheiro era grande, carregue-o novamente (completo) para obter a transcrição inteira.",
    "reupload_btn": "Carregar ficheiro completo",
    "uploading": "A carregar e a transcrever…",
    "eo_title": "Espere — deixamos-lhe mais barato",
    "eo_text": "A sua transcrição já está pronta. Leve-a hoje por {oferta} em vez de {normal}. {days} dias de acesso e, se não cancelar, a subscrição continua a {monthly}/mês.",
    "eo_accept": "Sim, quero a minha transcrição por {oferta}",
    "eo_decline": "Não, obrigado",
    "manual_unlock_title": "Desbloqueie a transcrição do seu vídeo",
    "manual_unlock_desc": "Obtenha o texto completo deste vídeo, editável e pronto a exportar em TXT, DOCX, PDF e SRT.",
    "manual_title": "A sua transcrição estará pronta em menos de 24 horas",
    "manual_desc": "Os vídeos desta plataforma são processados pela nossa equipa. Aparecerá aqui automaticamente assim que estiver pronta — guarde esta página.",
    "manual_email_q": "Quer receber um email quando estiver pronta?",
    "manual_email_btn": "Avisar-me",
    "manual_email_ok": "Feito! Enviaremos um email assim que estiver pronta.",
    "acct_title": "A minha conta",
    "acct_email": "Email",
    "acct_name": "Nome",
    "acct_sub": "Subscrição",
    "acct_status_none": "Sem subscrição",
    "acct_status_trial": "Em período de teste",
    "acct_status_active": "Ativa",
    "acct_status_pastdue": "Pagamento em atraso",
    "acct_status_canceled": "Cancelada",
    "acct_renews": "Renova em",
    "acct_ends": "Acesso até",
    "acct_trans": "Transcrições",
    "acct_cancel": "Cancelar subscrição",
    "acct_cancel_confirm": "Tem a certeza de que quer cancelar? Mantém o acesso até ao fim do período já pago.",
    "acct_canceled_note": "Subscrição cancelada. Mantém o acesso até {date}.",
    "acct_cancel_ok": "A sua subscrição foi cancelada. Mantém o acesso até ao fim do período.",
    "acct_see_plans": "Ver planos",
    "acct_cancel_err": "✗ Não foi possível cancelar. Escreva-nos para {email}.",
    "quota_title": "O teste de 7 dias inclui apenas uma transcrição",
    "quota_desc": "Se quiser transcrições ilimitadas, ative já o plano.",
    "quota_cta": "Ativar o meu plano agora",
    "quota_later": "Talvez mais tarde",
    "up_ok": "Plano mensal ativado! Já tem transcrições ilimitadas.",
    "acct_upgrade": "Passar ao plano mensal (ilimitado)",
    "thanks_title": "Pagamento concluído!",
    "thanks_sub": "A sua transcrição está a ser desbloqueada. Levamo-lo lá em poucos segundos…",
    "thanks_btn": "Ver a minha transcrição",
    "tt_h1": "Falar para texto — fale e receba tudo por escrito",
    "tt_sub": "Toque no microfone, comece a falar e tenha a sua voz convertida em texto em segundos. Funciona no navegador.",
    "tt_meta_title": "Falar para texto — dite com a sua voz e converta-a em texto online",
    "tt_meta_desc": "Converta a sua voz em texto ao instante: toque no microfone, fale e exporte a transcrição em TXT, DOCX, PDF ou SRT. Mais de 90 idiomas, funciona no navegador.",
    "mic_tap": "Toque para começar a gravar",
    "mic_recording": "A gravar",
    "mic_stop": "Toque no botão para terminar",
    "mic_again": "Gravar novamente",
    "mic_start": "Iniciar transcrição",
    "mic_uploading": "A carregar e a transcrever…",
    "mic_denied": "Não conseguimos aceder ao seu microfone. Permita o acesso no navegador e tente novamente.",
    "tt_or": "Já tem um ficheiro de áudio ou vídeo?",
    "tt_upload": "Carregue-o aqui",
    "up_drag": "ou arraste e largue o seu ficheiro aqui",
    "up_url_link": "Também pode colar um URL",
    "up_url_ph": "Cole aqui o seu link (YouTube, etc.)",
    "up_transcribe": "Transcrever",
    "up_uploading": "A carregar…",
    "up_err": "O carregamento falhou. Verifique a ligação e tente novamente.",
    "up_legal_pre": "Ao carregar um ficheiro ou URL aceita os nossos",
    "unlock_wait_title": "Pagamento recebido — a terminar a sua transcrição",
    "unlock_wait_sub": "Estamos a transcrever o texto completo. Aparecerá aqui sozinho em poucos segundos.",
    "up_fast_hint": "Transcrição rápida com IA",
    "up_langs_hint": "Mais de 90 idiomas",
    "up_url_hint": "Colar um URL",
    "up_mic_hint": "Gravar com o microfone",
    "pr_badge_trial": "Teste {today}",
    "pr_trial_line": "{today} nos primeiros {n} dias, depois {price}/{per}",
    "pr_err_pay": "⚠️ Não foi possível iniciar o pagamento. Tente novamente dentro de alguns minutos.",
    "pr_err_config": "⚠️ Este plano ainda não está disponível para pagamento. Tente novamente em breve.",
    "per_month": "mês",
    "per_year": "ano",
    "dash_new": "Nova transcrição",
    "dash_mine": "As minhas transcrições",
    "dash_empty": "Ainda não tem transcrições. Carregue o seu primeiro áudio ou vídeo acima.",
    "th_title": "Título",
    "th_lang": "Idioma",
    "th_mode": "Modo",
    "th_status": "Estado",
    "th_date": "Data",
    "open": "Abrir →",
    "st_done": "Pronta",
    "st_proc": "A processar",
    "st_manual": "⏳ Em curso · <24h",
    "st_queued": "Em fila",
    "st_err": "Erro",
    "err_nofile": "Carregue um ficheiro ou cole um URL.",
    "err_badtype": "Esse ficheiro não é um áudio ou vídeo válido. Formatos aceites: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "O ficheiro é demasiado grande.",
    "err_max": "(máximo {max} MB)",
    "err_infected": "O ficheiro foi rejeitado por segurança: o antivírus detetou uma ameaça.",
    "err_limit": "Fez várias tentativas seguidas. Aguarde um momento e tente novamente.",
    "back": "← Voltar",
    "logout": "Terminar sessão",
    "export_label": "Exportar:",
    "nav_dashboard": "O meu painel",
    "side_dash": "🏠 As minhas transcrições",
    "side_new": "➕ Nova",
    "side_account": "👤 A minha conta",
    "side_admin": "⚙️ Administração",
    "ed_saved": "Guardado ✓",
    "ed_saving": "A guardar…",
    "ed_copy": "Copiar",
    "ed_copied": "Copiado!",
    "err_generic": "Não foi possível processar o carregamento."
  },
  "fr": {
    "proc_title": "Préparation de votre transcription…",
    "proc_sub": "Nous traitons votre audio pour plus de précision.",
    "err": "La transcription a échoué. Essayez un autre fichier ou réessayez.",
    "missing": "Il vous manque {x} de la transcription",
    "unlock_title": "Débloquer la transcription",
    "pitch": "Ce n'est que le début. Débloquez la transcription complète, modifiez-la et exportez-la en TXT, DOCX, PDF et SRT.",
    "cta": "Débloquer maintenant — {today}",
    "cta_sub": "{today} pendant les {n} premiers jours, puis {price}/mois · Annulable à tout moment.",
    "expired": "Le fichier d'origine a expiré et a été supprimé. Après votre abonnement, importez-le à nouveau pour terminer la transcription.",
    "sec_edit": "Modifier",
    "sec_export": "Exporter",
    "sec_more": "Plus",
    "it_search": "Rechercher et remplacer",
    "it_save": "Enregistrer les modifications",
    "it_pdf": "Télécharger en PDF",
    "it_docx": "Télécharger en DOCX",
    "it_txt": "Télécharger en TXT",
    "it_srt": "Télécharger en SRT",
    "it_ts": "Afficher les horodatages",
    "it_translate": "Traduire",
    "it_share": "Partager la transcription",
    "it_audio": "Télécharger l'audio",
    "it_rename": "Renommer le fichier",
    "it_move": "Déplacer",
    "it_delete": "Supprimer le fichier",
    "item_locked": "Débloquez pour utiliser cette option",
    "pay_today": "À payer aujourd'hui",
    "pay_desc": "{n} jours d'accès complet. Puis {price}/mois. Annulable à tout moment.",
    "email": "E-mail",
    "loading_pay": "Chargement du paiement sécurisé…",
    "processing": "Traitement…",
    "legal_pre": "En continuant, vous acceptez nos",
    "legal_terms": "Conditions",
    "legal_sub": "Abonnement et remboursements",
    "legal_privacy": "Confidentialité",
    "pay_secure": "Paiement sécurisé avec Stripe.",
    "email_invalid": "Saisissez une adresse e-mail valide.",
    "pay_error": "Le paiement n'a pas pu être traité.",
    "reupload_title": "Importez votre fichier complet",
    "reupload_desc": "Votre abonnement est actif. Comme le fichier était volumineux, importez-le à nouveau (en entier) pour obtenir la transcription complète.",
    "reupload_btn": "Importer le fichier complet",
    "uploading": "Import et transcription en cours…",
    "eo_title": "Attendez — on vous la fait moins chère",
    "eo_text": "Votre transcription est prête. Emportez-la aujourd'hui pour {oferta} au lieu de {normal}. {days} jours d'accès et, sauf annulation, l'abonnement continue à {monthly}/mois.",
    "eo_accept": "Oui, je veux ma transcription pour {oferta}",
    "eo_decline": "Non, merci",
    "manual_unlock_title": "Débloquez la transcription de votre vidéo",
    "manual_unlock_desc": "Obtenez le texte complet de cette vidéo, modifiable et prêt à exporter en TXT, DOCX, PDF et SRT.",
    "manual_title": "Votre transcription sera prête en moins de 24 heures",
    "manual_desc": "Les vidéos de cette plateforme sont traitées par notre équipe. Elle apparaîtra ici automatiquement dès qu'elle sera prête — conservez cette page.",
    "manual_email_q": "Voulez-vous un e-mail quand elle sera prête ?",
    "manual_email_btn": "Me prévenir",
    "manual_email_ok": "C'est noté ! Nous vous écrirons dès qu'elle sera prête.",
    "acct_title": "Mon compte",
    "acct_email": "E-mail",
    "acct_name": "Nom",
    "acct_sub": "Abonnement",
    "acct_status_none": "Sans abonnement",
    "acct_status_trial": "En période d'essai",
    "acct_status_active": "Actif",
    "acct_status_pastdue": "Paiement en retard",
    "acct_status_canceled": "Annulé",
    "acct_renews": "Renouvellement le",
    "acct_ends": "Accès jusqu'au",
    "acct_trans": "Transcriptions",
    "acct_cancel": "Annuler l'abonnement",
    "acct_cancel_confirm": "Voulez-vous vraiment annuler ? Vous gardez l'accès jusqu'à la fin de la période déjà payée.",
    "acct_canceled_note": "Abonnement annulé. Vous gardez l'accès jusqu'au {date}.",
    "acct_cancel_ok": "Votre abonnement a été annulé. Vous gardez l'accès jusqu'à la fin de la période.",
    "acct_see_plans": "Voir les offres",
    "acct_cancel_err": "✗ Impossible d'annuler. Écrivez-nous à {email}.",
    "quota_title": "L'essai de 7 jours ne comprend qu'une seule transcription",
    "quota_desc": "Pour des transcriptions illimitées, activez l'offre maintenant.",
    "quota_cta": "Activer mon offre maintenant",
    "quota_later": "Plus tard",
    "up_ok": "Offre mensuelle activée ! Vous avez maintenant des transcriptions illimitées.",
    "acct_upgrade": "Passer à l'offre mensuelle (illimitée)",
    "thanks_title": "Paiement effectué !",
    "thanks_sub": "Votre transcription est en cours de déblocage. Nous vous y emmenons dans quelques secondes…",
    "thanks_btn": "Voir ma transcription",
    "tt_h1": "Parler pour écrire — dictez, et recevez le texte",
    "tt_sub": "Appuyez sur le micro, parlez et obtenez votre voix convertie en texte en quelques secondes. Fonctionne dans le navigateur.",
    "tt_meta_title": "Dictée vocale — parlez et convertissez votre voix en texte en ligne",
    "tt_meta_desc": "Convertissez votre voix en texte instantanément : appuyez sur le micro, parlez et exportez la transcription en TXT, DOCX, PDF ou SRT. Plus de 90 langues, dans le navigateur.",
    "mic_tap": "Appuyez pour commencer l'enregistrement",
    "mic_recording": "Enregistrement",
    "mic_stop": "Appuyez sur le bouton pour terminer",
    "mic_again": "Réenregistrer",
    "mic_start": "Lancer la transcription",
    "mic_uploading": "Import et transcription…",
    "mic_denied": "Impossible d'accéder à votre micro. Autorisez l'accès au micro dans votre navigateur et réessayez.",
    "tt_or": "Vous avez déjà un fichier audio ou vidéo ?",
    "tt_upload": "Importez-le ici",
    "up_drag": "ou glissez-déposez votre fichier ici",
    "up_url_link": "Vous pouvez aussi coller une URL",
    "up_url_ph": "Collez votre lien ici (YouTube, etc.)",
    "up_transcribe": "Transcrire",
    "up_uploading": "Import en cours…",
    "up_err": "L'import a échoué. Vérifiez votre connexion et réessayez.",
    "up_legal_pre": "En important un fichier ou une URL, vous acceptez nos",
    "unlock_wait_title": "Paiement reçu — nous terminons votre transcription",
    "unlock_wait_sub": "Nous transcrivons le texte complet. Il apparaîtra ici tout seul dans quelques secondes.",
    "up_fast_hint": "Transcription IA rapide",
    "up_langs_hint": "Plus de 90 langues",
    "up_url_hint": "Coller une URL",
    "up_mic_hint": "Enregistrer avec votre micro",
    "pr_badge_trial": "Essai {today}",
    "pr_trial_line": "{today} les {n} premiers jours, puis {price}/{per}",
    "pr_err_pay": "⚠️ Impossible de lancer le paiement. Réessayez dans quelques minutes.",
    "pr_err_config": "⚠️ Cette offre n'est pas encore disponible au paiement. Réessayez bientôt.",
    "per_month": "mois",
    "per_year": "an",
    "dash_new": "Nouvelle transcription",
    "dash_mine": "Mes transcriptions",
    "dash_empty": "Vous n'avez pas encore de transcription. Importez votre premier audio ou vidéo ci-dessus.",
    "th_title": "Titre",
    "th_lang": "Langue",
    "th_mode": "Mode",
    "th_status": "Statut",
    "th_date": "Date",
    "open": "Ouvrir →",
    "st_done": "Prête",
    "st_proc": "En cours",
    "st_manual": "⏳ En cours · <24h",
    "st_queued": "En attente",
    "st_err": "Erreur",
    "err_nofile": "Importez un fichier ou collez une URL.",
    "err_badtype": "Ce fichier n'est pas un audio ou une vidéo valide. Formats acceptés : MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "Le fichier est trop volumineux.",
    "err_max": "(maximum {max} Mo)",
    "err_infected": "Le fichier a été refusé pour des raisons de sécurité : l'antivirus a détecté une menace.",
    "err_limit": "Vous avez fait plusieurs essais d'affilée. Patientez un instant et réessayez.",
    "back": "← Retour",
    "logout": "Se déconnecter",
    "export_label": "Exporter :",
    "nav_dashboard": "Mon espace",
    "side_dash": "🏠 Mes transcriptions",
    "side_new": "➕ Nouvelle",
    "side_account": "👤 Mon compte",
    "side_admin": "⚙️ Administration",
    "ed_saved": "Enregistré ✓",
    "ed_saving": "Enregistrement…",
    "ed_copy": "Copier",
    "ed_copied": "Copié !",
    "err_generic": "L'import n'a pas pu être traité."
  },
  "de": {
    "proc_title": "Transkription wird vorbereitet…",
    "proc_sub": "Wir verarbeiten dein Audio für höchste Genauigkeit.",
    "err": "Transkription fehlgeschlagen. Versuche eine andere Datei oder versuche es erneut.",
    "missing": "Dir fehlen {x} der Transkription",
    "unlock_title": "Transkription freischalten",
    "pitch": "Das ist erst der Anfang. Schalten Sie die vollständige Transkription frei, bearbeiten Sie sie und exportieren Sie sie als TXT, DOCX, PDF und SRT.",
    "cta": "Jetzt freischalten — {today}",
    "cta_sub": "{today} für die ersten {n} Tage, danach {price}/Monat · Jederzeit kündbar.",
    "expired": "Die Originaldatei ist abgelaufen und wurde gelöscht. Laden Sie sie nach dem Abschluss des Abos erneut hoch, um die Transkription abzuschließen.",
    "sec_edit": "Bearbeiten",
    "sec_export": "Exportieren",
    "sec_more": "Mehr",
    "it_search": "Suchen und ersetzen",
    "it_save": "Änderungen speichern",
    "it_pdf": "PDF herunterladen",
    "it_docx": "DOCX herunterladen",
    "it_txt": "TXT herunterladen",
    "it_srt": "SRT herunterladen",
    "it_ts": "Zeitstempel anzeigen",
    "it_translate": "Übersetzen",
    "it_share": "Transkription teilen",
    "it_audio": "Audio herunterladen",
    "it_rename": "Datei umbenennen",
    "it_move": "Verschieben",
    "it_delete": "Datei löschen",
    "item_locked": "Freischalten, um diese Option zu nutzen",
    "pay_today": "Heute fällig",
    "pay_desc": "{n} Tage voller Zugriff. Danach {price}/Monat. Jederzeit kündbar.",
    "email": "E-Mail",
    "loading_pay": "Sichere Zahlung wird geladen…",
    "processing": "Wird verarbeitet…",
    "legal_pre": "Wenn du fortfährst, akzeptierst du unsere",
    "legal_terms": "AGB",
    "legal_sub": "Abo & Rückerstattungen",
    "legal_privacy": "Datenschutz",
    "pay_secure": "Sichere Zahlung mit Stripe.",
    "email_invalid": "Gib eine gültige E-Mail-Adresse ein.",
    "pay_error": "Zahlung konnte nicht verarbeitet werden.",
    "reupload_title": "Laden Sie Ihre vollständige Datei hoch",
    "reupload_desc": "Ihr Abo ist aktiv. Da die Datei groß war, laden Sie sie bitte erneut (vollständig) hoch, um die komplette Transkription zu erhalten.",
    "reupload_btn": "Vollständige Datei hochladen",
    "uploading": "Wird hochgeladen und transkribiert…",
    "eo_title": "Moment — wir machen es Ihnen günstiger",
    "eo_text": "Ihre Transkription ist fertig. Holen Sie sie sich heute für {oferta} statt {normal}. {days} Tage Zugang, und wenn Sie nicht kündigen, läuft das Abo für {monthly}/Monat weiter.",
    "eo_accept": "Ja, ich möchte meine Transkription für {oferta}",
    "eo_decline": "Nein, danke",
    "manual_unlock_title": "Schalten Sie die Transkription Ihres Videos frei",
    "manual_unlock_desc": "Erhalten Sie den vollständigen Text dieses Videos, bearbeitbar und bereit zum Export als TXT, DOCX, PDF und SRT.",
    "manual_title": "Ihre Transkription ist in weniger als 24 Stunden fertig",
    "manual_desc": "Videos dieser Plattform werden von unserem Team bearbeitet. Sie erscheint hier automatisch, sobald sie fertig ist — behalten Sie diese Seite.",
    "manual_email_q": "Möchten Sie eine E-Mail, sobald sie fertig ist?",
    "manual_email_btn": "Benachrichtigen",
    "manual_email_ok": "Erledigt! Wir schreiben Ihnen, sobald sie fertig ist.",
    "acct_title": "Mein Konto",
    "acct_email": "E-Mail",
    "acct_name": "Name",
    "acct_sub": "Abo",
    "acct_status_none": "Kein Abo",
    "acct_status_trial": "In der Testphase",
    "acct_status_active": "Aktiv",
    "acct_status_pastdue": "Zahlung überfällig",
    "acct_status_canceled": "Gekündigt",
    "acct_renews": "Verlängert sich am",
    "acct_ends": "Zugang bis",
    "acct_trans": "Transkriptionen",
    "acct_cancel": "Abo kündigen",
    "acct_cancel_confirm": "Möchten Sie wirklich kündigen? Sie behalten den Zugang bis zum Ende des bereits bezahlten Zeitraums.",
    "acct_canceled_note": "Abo gekündigt. Sie behalten den Zugang bis {date}.",
    "acct_cancel_ok": "Ihr Abo wurde gekündigt. Sie behalten den Zugang bis zum Ende des Zeitraums.",
    "acct_see_plans": "Tarife ansehen",
    "acct_cancel_err": "✗ Die Kündigung war nicht möglich. Schreiben Sie uns an {email}.",
    "quota_title": "Die 7-tägige Testphase enthält nur eine Transkription",
    "quota_desc": "Wenn Sie unbegrenzte Transkriptionen möchten, aktivieren Sie jetzt den Tarif.",
    "quota_cta": "Meinen Tarif jetzt aktivieren",
    "quota_later": "Vielleicht später",
    "up_ok": "Monatstarif aktiviert! Sie haben jetzt unbegrenzte Transkriptionen.",
    "acct_upgrade": "Zum Monatstarif wechseln (unbegrenzt)",
    "thanks_title": "Zahlung abgeschlossen!",
    "thanks_sub": "Ihre Transkription wird freigeschaltet. Wir bringen Sie in wenigen Sekunden dorthin…",
    "thanks_btn": "Meine Transkription ansehen",
    "tt_h1": "Sprache zu Text — sprechen Sie, und erhalten Sie es schriftlich",
    "tt_sub": "Tippen Sie auf das Mikrofon, sprechen Sie und erhalten Sie Ihre Stimme in Sekunden als Text. Funktioniert im Browser.",
    "tt_meta_title": "Sprache zu Text — diktieren Sie und wandeln Sie Ihre Stimme online in Text um",
    "tt_meta_desc": "Wandeln Sie Ihre Stimme sofort in Text um: Mikrofon antippen, sprechen und die Transkription als TXT, DOCX, PDF oder SRT exportieren. Über 90 Sprachen, direkt im Browser.",
    "mic_tap": "Antippen, um die Aufnahme zu starten",
    "mic_recording": "Aufnahme läuft",
    "mic_stop": "Tippen Sie auf die Schaltfläche, um zu beenden",
    "mic_again": "Erneut aufnehmen",
    "mic_start": "Transkription starten",
    "mic_uploading": "Wird hochgeladen und transkribiert…",
    "mic_denied": "Wir konnten nicht auf Ihr Mikrofon zugreifen. Erlauben Sie den Mikrofonzugriff im Browser und versuchen Sie es erneut.",
    "tt_or": "Sie haben bereits eine Audio- oder Videodatei?",
    "tt_upload": "Hier hochladen",
    "up_drag": "oder ziehen Sie Ihre Datei hierher",
    "up_url_link": "Sie können auch eine URL einfügen",
    "up_url_ph": "Fügen Sie hier Ihren Link ein (YouTube usw.)",
    "up_transcribe": "Transkribieren",
    "up_uploading": "Wird hochgeladen…",
    "up_err": "Der Upload ist fehlgeschlagen. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
    "up_legal_pre": "Mit dem Hochladen einer Datei oder URL akzeptieren Sie unsere",
    "unlock_wait_title": "Zahlung erhalten — Ihre Transkription wird fertiggestellt",
    "unlock_wait_sub": "Wir transkribieren den vollständigen Text. Er erscheint hier in wenigen Sekunden von selbst.",
    "up_fast_hint": "Schnelle KI-Transkription",
    "up_langs_hint": "Über 90 Sprachen",
    "up_url_hint": "URL einfügen",
    "up_mic_hint": "Mit dem Mikrofon aufnehmen",
    "pr_badge_trial": "Test {today}",
    "pr_trial_line": "{today} für die ersten {n} Tage, danach {price}/{per}",
    "pr_err_pay": "⚠️ Die Zahlung konnte nicht gestartet werden. Versuchen Sie es in ein paar Minuten erneut.",
    "pr_err_config": "⚠️ Dieser Tarif ist noch nicht zur Zahlung verfügbar. Versuchen Sie es bald erneut.",
    "per_month": "Monat",
    "per_year": "Jahr",
    "dash_new": "Neue Transkription",
    "dash_mine": "Meine Transkriptionen",
    "dash_empty": "Sie haben noch keine Transkriptionen. Laden Sie oben Ihre erste Audio- oder Videodatei hoch.",
    "th_title": "Titel",
    "th_lang": "Sprache",
    "th_mode": "Modus",
    "th_status": "Status",
    "th_date": "Datum",
    "open": "Öffnen →",
    "st_done": "Fertig",
    "st_proc": "In Bearbeitung",
    "st_manual": "⏳ In Bearbeitung · <24h",
    "st_queued": "In der Warteschlange",
    "st_err": "Fehler",
    "err_nofile": "Laden Sie eine Datei hoch oder fügen Sie eine URL ein.",
    "err_badtype": "Diese Datei ist keine gültige Audio- oder Videodatei. Unterstützte Formate: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "Die Datei ist zu groß.",
    "err_max": "(maximal {max} MB)",
    "err_infected": "Die Datei wurde aus Sicherheitsgründen abgelehnt: Der Virenscanner hat eine Bedrohung erkannt.",
    "err_limit": "Sie haben mehrere Versuche hintereinander gemacht. Warten Sie einen Moment und versuchen Sie es erneut.",
    "back": "← Zurück",
    "logout": "Abmelden",
    "export_label": "Exportieren:",
    "nav_dashboard": "Mein Bereich",
    "side_dash": "🏠 Meine Transkriptionen",
    "side_new": "➕ Neu",
    "side_account": "👤 Mein Konto",
    "side_admin": "⚙️ Verwaltung",
    "ed_saved": "Gespeichert ✓",
    "ed_saving": "Wird gespeichert…",
    "ed_copy": "Kopieren",
    "ed_copied": "Kopiert!",
    "err_generic": "Der Upload konnte nicht verarbeitet werden."
  },
  "it": {
    "proc_title": "Preparazione della trascrizione…",
    "proc_sub": "Stiamo elaborando il tuo audio per garantire la precisione.",
    "err": "Non siamo riusciti a trascriverlo. Prova con un altro file o riprova.",
    "missing": "Ti manca {x} di trascrizione",
    "unlock_title": "Sblocca la trascrizione",
    "pitch": "Questo è solo l'inizio. Sblocca la trascrizione completa, modificala ed esportala in TXT, DOCX, PDF e SRT.",
    "cta": "Sblocca ora — {today}",
    "cta_sub": "{today} per i primi {n} giorni, poi {price}/mese · Disdici quando vuoi.",
    "expired": "Il file originale è scaduto ed è stato eliminato. Dopo l'abbonamento, caricalo di nuovo per completare la trascrizione.",
    "sec_edit": "Modifica",
    "sec_export": "Esporta",
    "sec_more": "Altro",
    "it_search": "Trova e sostituisci",
    "it_save": "Salva le modifiche",
    "it_pdf": "Scarica PDF",
    "it_docx": "Scarica DOCX",
    "it_txt": "Scarica TXT",
    "it_srt": "Scarica SRT",
    "it_ts": "Mostra timestamp",
    "it_translate": "Traduci",
    "it_share": "Condividi trascrizione",
    "it_audio": "Scarica audio",
    "it_rename": "Rinomina file",
    "it_move": "Sposta",
    "it_delete": "Elimina file",
    "item_locked": "Sblocca per usare questa opzione",
    "pay_today": "Da pagare oggi",
    "pay_desc": "{n} giorni di accesso completo. Poi {price}/mese. Disdici quando vuoi.",
    "email": "Email",
    "loading_pay": "Caricamento del pagamento sicuro…",
    "processing": "Elaborazione…",
    "legal_pre": "Continuando accetti i nostri",
    "legal_terms": "Termini",
    "legal_sub": "Abbonamento e rimborsi",
    "legal_privacy": "Privacy",
    "pay_secure": "Pagamento sicuro con Stripe.",
    "email_invalid": "Inserisci un'email valida.",
    "pay_error": "Impossibile elaborare il pagamento.",
    "reupload_title": "Carica il tuo file completo",
    "reupload_desc": "Il tuo abbonamento è attivo. Poiché il file era grande, caricalo di nuovo (per intero) per ottenere la trascrizione completa.",
    "reupload_btn": "Carica il file completo",
    "uploading": "Caricamento e trascrizione in corso…",
    "eo_title": "Aspetta — te la facciamo a meno",
    "eo_text": "La tua trascrizione è pronta. Portala a casa oggi a {oferta} invece di {normal}. {days} giorni di accesso e, se non disdici, l'abbonamento continua a {monthly}/mese.",
    "eo_accept": "Sì, voglio la mia trascrizione a {oferta}",
    "eo_decline": "No, grazie",
    "manual_unlock_title": "Sblocca la trascrizione del tuo video",
    "manual_unlock_desc": "Ottieni il testo completo di questo video, modificabile e pronto da esportare in TXT, DOCX, PDF e SRT.",
    "manual_title": "La tua trascrizione sarà pronta in meno di 24 ore",
    "manual_desc": "I video di questa piattaforma vengono elaborati dal nostro team. Apparirà qui automaticamente non appena sarà pronta — conserva questa pagina.",
    "manual_email_q": "Vuoi un'email quando sarà pronta?",
    "manual_email_btn": "Avvisami",
    "manual_email_ok": "Fatto! Ti scriveremo non appena sarà pronta.",
    "acct_title": "Il mio account",
    "acct_email": "Email",
    "acct_name": "Nome",
    "acct_sub": "Abbonamento",
    "acct_status_none": "Nessun abbonamento",
    "acct_status_trial": "In periodo di prova",
    "acct_status_active": "Attivo",
    "acct_status_pastdue": "Pagamento in ritardo",
    "acct_status_canceled": "Disdetto",
    "acct_renews": "Si rinnova il",
    "acct_ends": "Accesso fino al",
    "acct_trans": "Trascrizioni",
    "acct_cancel": "Disdici l'abbonamento",
    "acct_cancel_confirm": "Sei sicuro di voler disdire? Manterrai l'accesso fino alla fine del periodo già pagato.",
    "acct_canceled_note": "Abbonamento disdetto. Mantieni l'accesso fino al {date}.",
    "acct_cancel_ok": "Il tuo abbonamento è stato disdetto. Mantieni l'accesso fino alla fine del periodo.",
    "acct_see_plans": "Vedi i piani",
    "acct_cancel_err": "✗ Non è stato possibile disdire. Scrivici a {email}.",
    "quota_title": "La prova di 7 giorni include una sola trascrizione",
    "quota_desc": "Se vuoi trascrizioni illimitate, attiva subito il piano.",
    "quota_cta": "Attiva subito il mio piano",
    "quota_later": "Forse più tardi",
    "up_ok": "Piano mensile attivato! Ora hai trascrizioni illimitate.",
    "acct_upgrade": "Passa al piano mensile (illimitato)",
    "thanks_title": "Pagamento completato!",
    "thanks_sub": "La tua trascrizione si sta sbloccando. Ti portiamo lì tra pochi secondi…",
    "thanks_btn": "Vedi la mia trascrizione",
    "tt_h1": "Parla e scrivi — detta, e ricevilo per iscritto",
    "tt_sub": "Tocca il microfono, inizia a parlare e ottieni la tua voce convertita in testo in pochi secondi. Funziona nel browser.",
    "tt_meta_title": "Da voce a testo — detta con la tua voce e convertila in testo online",
    "tt_meta_desc": "Converti la tua voce in testo all'istante: tocca il microfono, parla ed esporta la trascrizione in TXT, DOCX, PDF o SRT. Oltre 90 lingue, direttamente nel browser.",
    "mic_tap": "Tocca per iniziare a registrare",
    "mic_recording": "Registrazione in corso",
    "mic_stop": "Tocca il pulsante per terminare",
    "mic_again": "Registra di nuovo",
    "mic_start": "Avvia la trascrizione",
    "mic_uploading": "Caricamento e trascrizione…",
    "mic_denied": "Non riusciamo ad accedere al microfono. Consenti l'accesso al microfono nel browser e riprova.",
    "tt_or": "Hai già un file audio o video?",
    "tt_upload": "Caricalo qui",
    "up_drag": "oppure trascina qui il tuo file",
    "up_url_link": "Puoi anche incollare un URL",
    "up_url_ph": "Incolla qui il tuo link (YouTube, ecc.)",
    "up_transcribe": "Trascrivi",
    "up_uploading": "Caricamento…",
    "up_err": "Caricamento non riuscito. Controlla la connessione e riprova.",
    "up_legal_pre": "Caricando un file o un URL accetti i nostri",
    "unlock_wait_title": "Pagamento ricevuto — stiamo completando la tua trascrizione",
    "unlock_wait_sub": "Stiamo trascrivendo il testo completo. Apparirà qui da solo tra pochi secondi.",
    "up_fast_hint": "Trascrizione IA veloce",
    "up_langs_hint": "Oltre 90 lingue",
    "up_url_hint": "Incolla un URL",
    "up_mic_hint": "Registra con il microfono",
    "pr_badge_trial": "Prova {today}",
    "pr_trial_line": "{today} per i primi {n} giorni, poi {price}/{per}",
    "pr_err_pay": "⚠️ Non è stato possibile avviare il pagamento. Riprova tra qualche minuto.",
    "pr_err_config": "⚠️ Questo piano non è ancora disponibile per il pagamento. Riprova a breve.",
    "per_month": "mese",
    "per_year": "anno",
    "dash_new": "Nuova trascrizione",
    "dash_mine": "Le mie trascrizioni",
    "dash_empty": "Non hai ancora trascrizioni. Carica il tuo primo audio o video qui sopra.",
    "th_title": "Titolo",
    "th_lang": "Lingua",
    "th_mode": "Modalità",
    "th_status": "Stato",
    "th_date": "Data",
    "open": "Apri →",
    "st_done": "Pronta",
    "st_proc": "In elaborazione",
    "st_manual": "⏳ In lavorazione · <24h",
    "st_queued": "In coda",
    "st_err": "Errore",
    "err_nofile": "Carica un file o incolla un URL.",
    "err_badtype": "Quel file non è un audio o un video valido. Formati accettati: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "Il file è troppo grande.",
    "err_max": "(massimo {max} MB)",
    "err_infected": "Il file è stato rifiutato per sicurezza: l'antivirus ha rilevato una minaccia.",
    "err_limit": "Hai fatto diversi tentativi di seguito. Aspetta un momento e riprova.",
    "back": "← Indietro",
    "logout": "Esci",
    "export_label": "Esporta:",
    "nav_dashboard": "Il mio pannello",
    "side_dash": "🏠 Le mie trascrizioni",
    "side_new": "➕ Nuova",
    "side_account": "👤 Il mio account",
    "side_admin": "⚙️ Amministrazione",
    "ed_saved": "Salvato ✓",
    "ed_saving": "Salvataggio…",
    "ed_copy": "Copia",
    "ed_copied": "Copiato!",
    "err_generic": "Non è stato possibile elaborare il caricamento."
  },
  "nl": {
    "proc_title": "Je transcriptie wordt voorbereid…",
    "proc_sub": "We verwerken je audio voor de nauwkeurigheid.",
    "err": "We konden het niet transcriberen. Probeer een ander bestand of probeer het opnieuw.",
    "missing": "Je mist {x} van de transcriptie",
    "unlock_title": "Ontgrendel de transcriptie",
    "pitch": "Dit is nog maar het begin. Ontgrendel de volledige transcriptie, bewerk deze en exporteer deze als TXT, DOCX, PDF en SRT.",
    "cta": "Nu ontgrendelen — {today}",
    "cta_sub": "{today} voor de eerste {n} dagen, daarna {price}/mnd · Altijd opzegbaar.",
    "expired": "Het originele bestand is verlopen en verwijderd. Upload het na je abonnement opnieuw om de transcriptie af te maken.",
    "sec_edit": "Bewerken",
    "sec_export": "Exporteren",
    "sec_more": "Meer",
    "it_search": "Zoeken en vervangen",
    "it_save": "Wijzigingen opslaan",
    "it_pdf": "PDF downloaden",
    "it_docx": "DOCX downloaden",
    "it_txt": "TXT downloaden",
    "it_srt": "SRT downloaden",
    "it_ts": "Tijdstempels tonen",
    "it_translate": "Vertalen",
    "it_share": "Transcriptie delen",
    "it_audio": "Audio downloaden",
    "it_rename": "Bestand hernoemen",
    "it_move": "Verplaatsen",
    "it_delete": "Bestand verwijderen",
    "item_locked": "Ontgrendel om deze optie te gebruiken",
    "pay_today": "Vandaag te betalen",
    "pay_desc": "{n} dagen volledige toegang. Daarna {price}/mnd. Altijd opzegbaar.",
    "email": "E-mail",
    "loading_pay": "Beveiligde betaling laden…",
    "processing": "Verwerken…",
    "legal_pre": "Door verder te gaan ga je akkoord met onze",
    "legal_terms": "Voorwaarden",
    "legal_sub": "Abonnement & terugbetalingen",
    "legal_privacy": "Privacy",
    "pay_secure": "Veilig betalen met Stripe.",
    "email_invalid": "Voer een geldig e-mailadres in.",
    "pay_error": "De betaling kon niet worden verwerkt.",
    "reupload_title": "Upload je volledige bestand",
    "reupload_desc": "Je abonnement is actief. Omdat het bestand groot was, upload je het opnieuw (volledig) om de hele transcriptie te krijgen.",
    "reupload_btn": "Volledig bestand uploaden",
    "uploading": "Uploaden en transcriberen…",
    "eo_title": "Wacht — we maken het goedkoper voor je",
    "eo_text": "Je transcriptie is klaar. Neem hem vandaag mee voor {oferta} in plaats van {normal}. {days} dagen toegang en, tenzij je opzegt, loopt het abonnement door voor {monthly}/maand.",
    "eo_accept": "Ja, ik wil mijn transcriptie voor {oferta}",
    "eo_decline": "Nee, bedankt",
    "manual_unlock_title": "Ontgrendel de transcriptie van je video",
    "manual_unlock_desc": "Krijg de volledige tekst van deze video, bewerkbaar en klaar om te exporteren als TXT, DOCX, PDF en SRT.",
    "manual_title": "Je transcriptie is binnen 24 uur klaar",
    "manual_desc": "Video's van dit platform worden door ons team verwerkt. Hij verschijnt hier automatisch zodra hij klaar is — bewaar deze pagina.",
    "manual_email_q": "Wil je een e-mail zodra hij klaar is?",
    "manual_email_btn": "Stuur me een bericht",
    "manual_email_ok": "Geregeld! We mailen je zodra hij klaar is.",
    "acct_title": "Mijn account",
    "acct_email": "E-mail",
    "acct_name": "Naam",
    "acct_sub": "Abonnement",
    "acct_status_none": "Geen abonnement",
    "acct_status_trial": "In proefperiode",
    "acct_status_active": "Actief",
    "acct_status_pastdue": "Betaling achterstallig",
    "acct_status_canceled": "Opgezegd",
    "acct_renews": "Verlengt op",
    "acct_ends": "Toegang tot",
    "acct_trans": "Transcripties",
    "acct_cancel": "Abonnement opzeggen",
    "acct_cancel_confirm": "Weet je zeker dat je wilt opzeggen? Je houdt toegang tot het einde van de al betaalde periode.",
    "acct_canceled_note": "Abonnement opgezegd. Je houdt toegang tot {date}.",
    "acct_cancel_ok": "Je abonnement is opgezegd. Je houdt toegang tot het einde van de periode.",
    "acct_see_plans": "Bekijk de abonnementen",
    "acct_cancel_err": "✗ Opzeggen is niet gelukt. Mail ons op {email}.",
    "quota_title": "De proefperiode van 7 dagen bevat maar één transcriptie",
    "quota_desc": "Wil je onbeperkt transcriberen? Activeer dan nu het abonnement.",
    "quota_cta": "Mijn abonnement nu activeren",
    "quota_later": "Misschien later",
    "up_ok": "Maandabonnement geactiveerd! Je hebt nu onbeperkte transcripties.",
    "acct_upgrade": "Overstappen naar het maandabonnement (onbeperkt)",
    "thanks_title": "Betaling voltooid!",
    "thanks_sub": "Je transcriptie wordt ontgrendeld. We brengen je er over een paar seconden heen…",
    "thanks_btn": "Mijn transcriptie bekijken",
    "tt_h1": "Spraak naar tekst — spreek, en krijg het op schrift",
    "tt_sub": "Tik op de microfoon, begin te praten en krijg je stem binnen seconden omgezet in tekst. Werkt in de browser.",
    "tt_meta_title": "Spraak naar tekst — dicteer met je stem en zet hem online om in tekst",
    "tt_meta_desc": "Zet je stem direct om in tekst: tik op de microfoon, spreek en exporteer de transcriptie als TXT, DOCX, PDF of SRT. Meer dan 90 talen, gewoon in de browser.",
    "mic_tap": "Tik om de opname te starten",
    "mic_recording": "Opname loopt",
    "mic_stop": "Tik op de knop om te stoppen",
    "mic_again": "Opnieuw opnemen",
    "mic_start": "Transcriptie starten",
    "mic_uploading": "Uploaden en transcriberen…",
    "mic_denied": "We kunnen je microfoon niet gebruiken. Geef de browser toegang tot de microfoon en probeer het opnieuw.",
    "tt_or": "Heb je al een audio- of videobestand?",
    "tt_upload": "Upload het hier",
    "up_drag": "of sleep je bestand hierheen",
    "up_url_link": "Je kunt ook een URL plakken",
    "up_url_ph": "Plak hier je link (YouTube, enz.)",
    "up_transcribe": "Transcriberen",
    "up_uploading": "Uploaden…",
    "up_err": "Uploaden is mislukt. Controleer je verbinding en probeer het opnieuw.",
    "up_legal_pre": "Door een bestand of URL te uploaden ga je akkoord met onze",
    "unlock_wait_title": "Betaling ontvangen — je transcriptie wordt afgerond",
    "unlock_wait_sub": "We transcriberen de volledige tekst. Hij verschijnt hier vanzelf over een paar seconden.",
    "up_fast_hint": "Snelle AI-transcriptie",
    "up_langs_hint": "Meer dan 90 talen",
    "up_url_hint": "Een URL plakken",
    "up_mic_hint": "Opnemen met je microfoon",
    "pr_badge_trial": "Proef {today}",
    "pr_trial_line": "{today} voor de eerste {n} dagen, daarna {price}/{per}",
    "pr_err_pay": "⚠️ De betaling kon niet worden gestart. Probeer het over een paar minuten opnieuw.",
    "pr_err_config": "⚠️ Dit abonnement is nog niet beschikbaar voor betaling. Probeer het binnenkort opnieuw.",
    "per_month": "maand",
    "per_year": "jaar",
    "dash_new": "Nieuwe transcriptie",
    "dash_mine": "Mijn transcripties",
    "dash_empty": "Je hebt nog geen transcripties. Upload hierboven je eerste audio of video.",
    "th_title": "Titel",
    "th_lang": "Taal",
    "th_mode": "Modus",
    "th_status": "Status",
    "th_date": "Datum",
    "open": "Openen →",
    "st_done": "Klaar",
    "st_proc": "Bezig",
    "st_manual": "⏳ In behandeling · <24u",
    "st_queued": "In de wachtrij",
    "st_err": "Fout",
    "err_nofile": "Upload een bestand of plak een URL.",
    "err_badtype": "Dat bestand is geen geldige audio of video. Ondersteunde formaten: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "Het bestand is te groot.",
    "err_max": "(maximaal {max} MB)",
    "err_infected": "Het bestand is om veiligheidsredenen geweigerd: de virusscanner heeft een bedreiging gevonden.",
    "err_limit": "Je hebt meerdere pogingen achter elkaar gedaan. Wacht even en probeer het opnieuw.",
    "back": "← Terug",
    "logout": "Uitloggen",
    "export_label": "Exporteren:",
    "nav_dashboard": "Mijn dashboard",
    "side_dash": "🏠 Mijn transcripties",
    "side_new": "➕ Nieuw",
    "side_account": "👤 Mijn account",
    "side_admin": "⚙️ Beheer",
    "ed_saved": "Opgeslagen ✓",
    "ed_saving": "Opslaan…",
    "ed_copy": "Kopiëren",
    "ed_copied": "Gekopieerd!",
    "err_generic": "De upload kon niet worden verwerkt."
  },
  "pl": {
    "proc_title": "Przygotowujemy transkrypcję…",
    "proc_sub": "Przetwarzamy Twoje audio, aby zapewnić dokładność.",
    "err": "Nie udało się utworzyć transkrypcji. Spróbuj z innym plikiem lub spróbuj ponownie.",
    "missing": "Brakuje Ci {x} transkrypcji",
    "unlock_title": "Odblokuj transkrypcję",
    "pitch": "To dopiero początek. Odblokuj pełną transkrypcję, edytuj ją i wyeksportuj w formatach TXT, DOCX, PDF i SRT.",
    "cta": "Odblokuj teraz — {today}",
    "cta_sub": "{today} przez pierwsze {n} dni, potem {price}/mies. · Anuluj w każdej chwili.",
    "expired": "Oryginalny plik wygasł i został usunięty. Po wykupieniu subskrypcji prześlij go ponownie, aby dokończyć transkrypcję.",
    "sec_edit": "Edycja",
    "sec_export": "Eksport",
    "sec_more": "Więcej",
    "it_search": "Znajdź i zamień",
    "it_save": "Zapisz zmiany",
    "it_pdf": "Pobierz PDF",
    "it_docx": "Pobierz DOCX",
    "it_txt": "Pobierz TXT",
    "it_srt": "Pobierz SRT",
    "it_ts": "Pokaż znaczniki czasu",
    "it_translate": "Przetłumacz",
    "it_share": "Udostępnij transkrypcję",
    "it_audio": "Pobierz audio",
    "it_rename": "Zmień nazwę pliku",
    "it_move": "Przenieś",
    "it_delete": "Usuń plik",
    "item_locked": "Odblokuj, aby użyć tej opcji",
    "pay_today": "Do zapłaty dziś",
    "pay_desc": "{n} dni pełnego dostępu. Potem {price}/mies. Anuluj w każdej chwili.",
    "email": "E-mail",
    "loading_pay": "Ładowanie bezpiecznej płatności…",
    "processing": "Przetwarzanie…",
    "legal_pre": "Kontynuując, akceptujesz nasze",
    "legal_terms": "Warunki",
    "legal_sub": "Subskrypcja i zwroty",
    "legal_privacy": "Prywatność",
    "pay_secure": "Bezpieczna płatność przez Stripe.",
    "email_invalid": "Podaj prawidłowy adres e-mail.",
    "pay_error": "Nie udało się przetworzyć płatności.",
    "reupload_title": "Prześlij pełny plik",
    "reupload_desc": "Twoja subskrypcja jest aktywna. Ponieważ plik był duży, prześlij go ponownie (w całości), aby otrzymać pełną transkrypcję.",
    "reupload_btn": "Prześlij pełny plik",
    "uploading": "Przesyłanie i transkrypcja…",
    "eo_title": "Chwila — damy Ci to taniej",
    "eo_text": "Twoja transkrypcja jest gotowa. Odbierz ją dziś za {oferta} zamiast {normal}. {days} dni dostępu, a jeśli nie anulujesz, subskrypcja trwa dalej za {monthly}/mies.",
    "eo_accept": "Tak, chcę moją transkrypcję za {oferta}",
    "eo_decline": "Nie, dziękuję",
    "manual_unlock_title": "Odblokuj transkrypcję swojego wideo",
    "manual_unlock_desc": "Otrzymaj pełny tekst tego wideo, gotowy do edycji i eksportu do TXT, DOCX, PDF i SRT.",
    "manual_title": "Twoja transkrypcja będzie gotowa w mniej niż 24 godziny",
    "manual_desc": "Wideo z tej platformy przetwarza nasz zespół. Pojawi się tutaj automatycznie, gdy będzie gotowe — zachowaj tę stronę.",
    "manual_email_q": "Chcesz dostać e-mail, gdy będzie gotowa?",
    "manual_email_btn": "Powiadom mnie",
    "manual_email_ok": "Gotowe! Napiszemy, gdy tylko będzie gotowa.",
    "acct_title": "Moje konto",
    "acct_email": "E-mail",
    "acct_name": "Imię i nazwisko",
    "acct_sub": "Subskrypcja",
    "acct_status_none": "Brak subskrypcji",
    "acct_status_trial": "Okres próbny",
    "acct_status_active": "Aktywna",
    "acct_status_pastdue": "Zaległa płatność",
    "acct_status_canceled": "Anulowana",
    "acct_renews": "Odnawia się",
    "acct_ends": "Dostęp do",
    "acct_trans": "Transkrypcje",
    "acct_cancel": "Anuluj subskrypcję",
    "acct_cancel_confirm": "Na pewno chcesz anulować? Zachowasz dostęp do końca opłaconego okresu.",
    "acct_canceled_note": "Subskrypcja anulowana. Zachowujesz dostęp do {date}.",
    "acct_cancel_ok": "Twoja subskrypcja została anulowana. Zachowujesz dostęp do końca okresu.",
    "acct_see_plans": "Zobacz plany",
    "acct_cancel_err": "✗ Nie udało się anulować. Napisz do nas na {email}.",
    "quota_title": "7-dniowy okres próbny obejmuje tylko jedną transkrypcję",
    "quota_desc": "Jeśli chcesz nielimitowanych transkrypcji, aktywuj plan już teraz.",
    "quota_cta": "Aktywuj mój plan teraz",
    "quota_later": "Może później",
    "up_ok": "Plan miesięczny aktywowany! Masz teraz nielimitowane transkrypcje.",
    "acct_upgrade": "Przejdź na plan miesięczny (bez limitu)",
    "thanks_title": "Płatność zakończona!",
    "thanks_sub": "Twoja transkrypcja jest odblokowywana. Za kilka sekund Cię tam przeniesiemy…",
    "thanks_btn": "Zobacz moją transkrypcję",
    "tt_h1": "Mowa na tekst — mów, a dostaniesz to na piśmie",
    "tt_sub": "Dotknij mikrofonu, zacznij mówić i w kilka sekund zamień swój głos w tekst. Działa w przeglądarce.",
    "tt_meta_title": "Mowa na tekst — dyktuj głosem i zamieniaj go w tekst online",
    "tt_meta_desc": "Zamień głos w tekst od razu: dotknij mikrofonu, mów i eksportuj transkrypcję do TXT, DOCX, PDF lub SRT. Ponad 90 języków, prosto w przeglądarce.",
    "mic_tap": "Dotknij, aby zacząć nagrywać",
    "mic_recording": "Nagrywanie",
    "mic_stop": "Dotknij przycisku, aby zakończyć",
    "mic_again": "Nagraj ponownie",
    "mic_start": "Rozpocznij transkrypcję",
    "mic_uploading": "Przesyłanie i transkrypcja…",
    "mic_denied": "Nie mamy dostępu do Twojego mikrofonu. Zezwól na dostęp do mikrofonu w przeglądarce i spróbuj ponownie.",
    "tt_or": "Masz już plik audio lub wideo?",
    "tt_upload": "Prześlij go tutaj",
    "up_drag": "lub przeciągnij i upuść plik tutaj",
    "up_url_link": "Możesz też wkleić adres URL",
    "up_url_ph": "Wklej tutaj swój link (YouTube itp.)",
    "up_transcribe": "Transkrybuj",
    "up_uploading": "Przesyłanie…",
    "up_err": "Przesyłanie nie powiodło się. Sprawdź połączenie i spróbuj ponownie.",
    "up_legal_pre": "Przesyłając plik lub adres URL, akceptujesz nasze",
    "unlock_wait_title": "Płatność otrzymana — kończymy Twoją transkrypcję",
    "unlock_wait_sub": "Transkrybujemy pełny tekst. Pojawi się tutaj sam za kilka sekund.",
    "up_fast_hint": "Szybka transkrypcja AI",
    "up_langs_hint": "Ponad 90 języków",
    "up_url_hint": "Wklej adres URL",
    "up_mic_hint": "Nagraj mikrofonem",
    "pr_badge_trial": "Próba {today}",
    "pr_trial_line": "{today} przez pierwsze {n} dni, potem {price}/{per}",
    "pr_err_pay": "⚠️ Nie udało się rozpocząć płatności. Spróbuj ponownie za kilka minut.",
    "pr_err_config": "⚠️ Ten plan nie jest jeszcze dostępny do zakupu. Spróbuj ponownie wkrótce.",
    "per_month": "mies.",
    "per_year": "rok",
    "dash_new": "Nowa transkrypcja",
    "dash_mine": "Moje transkrypcje",
    "dash_empty": "Nie masz jeszcze transkrypcji. Prześlij powyżej swoje pierwsze audio lub wideo.",
    "th_title": "Tytuł",
    "th_lang": "Język",
    "th_mode": "Tryb",
    "th_status": "Status",
    "th_date": "Data",
    "open": "Otwórz →",
    "st_done": "Gotowa",
    "st_proc": "Przetwarzanie",
    "st_manual": "⏳ W toku · <24h",
    "st_queued": "W kolejce",
    "st_err": "Błąd",
    "err_nofile": "Prześlij plik lub wklej adres URL.",
    "err_badtype": "Ten plik nie jest prawidłowym plikiem audio ani wideo. Obsługiwane formaty: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "Plik jest za duży.",
    "err_max": "(maksymalnie {max} MB)",
    "err_infected": "Plik został odrzucony ze względów bezpieczeństwa: antywirus wykrył zagrożenie.",
    "err_limit": "Wykonano kilka prób pod rząd. Odczekaj chwilę i spróbuj ponownie.",
    "back": "← Wstecz",
    "logout": "Wyloguj się",
    "export_label": "Eksportuj:",
    "nav_dashboard": "Mój panel",
    "side_dash": "🏠 Moje transkrypcje",
    "side_new": "➕ Nowa",
    "side_account": "👤 Moje konto",
    "side_admin": "⚙️ Administracja",
    "ed_saved": "Zapisano ✓",
    "ed_saving": "Zapisywanie…",
    "ed_copy": "Kopiuj",
    "ed_copied": "Skopiowano!",
    "err_generic": "Nie udało się przetworzyć przesyłania."
  },
  "el": {
    "proc_title": "Ετοιμάζουμε τη μεταγραφή σας…",
    "proc_sub": "Επεξεργαζόμαστε το ηχητικό σας για να είναι ακριβές.",
    "err": "Δεν ήταν δυνατή η μεταγραφή. Δοκιμάστε άλλο αρχείο ή προσπαθήστε ξανά.",
    "missing": "Σας λείπουν {x} μεταγραφής",
    "unlock_title": "Ξεκλειδώστε τη μεταγραφή",
    "pitch": "Αυτή είναι μόνο η αρχή. Ξεκλειδώστε την πλήρη μεταγραφή, επεξεργαστείτε την και εξαγάγετέ την σε TXT, DOCX, PDF και SRT.",
    "cta": "Ξεκλείδωμα τώρα — {today}",
    "cta_sub": "{today} τις πρώτες {n} ημέρες, μετά {price}/μήνα · Ακυρώστε όποτε θέλετε.",
    "sec_edit": "Επεξεργασία",
    "sec_export": "Εξαγωγή",
    "sec_more": "Περισσότερα",
    "pay_today": "Πληρωμή σήμερα",
    "pay_desc": "{n} ημέρες πλήρους πρόσβασης. Μετά {price}/μήνα. Ακυρώστε όποτε θέλετε.",
    "email": "Email",
    "loading_pay": "Φόρτωση ασφαλούς πληρωμής…",
    "processing": "Επεξεργασία…",
    "legal_pre": "Συνεχίζοντας αποδέχεστε τους",
    "legal_terms": "Όρους",
    "legal_sub": "Συνδρομή και επιστροφές",
    "legal_privacy": "Απόρρητο",
    "pay_secure": "Ασφαλής πληρωμή με Stripe.",
    "email_invalid": "Εισαγάγετε έγκυρο email.",
    "pay_error": "Δεν ήταν δυνατή η επεξεργασία της πληρωμής.",
    "manual_title": "Η μεταγραφή σας θα είναι έτοιμη σε λιγότερο από 24 ώρες",
    "manual_desc": "Τα βίντεο αυτής της πλατφόρμας τα επεξεργάζεται η ομάδα μας. Θα εμφανιστεί εδώ αυτόματα μόλις είναι έτοιμη — αποθηκεύστε αυτή τη σελίδα.",
    "manual_unlock_title": "Ξεκλειδώστε τη μεταγραφή του βίντεό σας",
    "manual_unlock_desc": "Αποκτήστε το πλήρες κείμενο αυτού του βίντεο, επεξεργάσιμο και έτοιμο για εξαγωγή σε TXT, DOCX, PDF και SRT.",
    "quota_title": "Η δοκιμή 7 ημερών περιλαμβάνει μόνο μία μεταγραφή",
    "quota_desc": "Αν θέλετε απεριόριστες μεταγραφές, ενεργοποιήστε το πλάνο τώρα.",
    "quota_cta": "Ενεργοποίηση του πλάνου μου",
    "quota_later": "Ίσως αργότερα",
    "up_drag": "ή σύρετε και αποθέστε το αρχείο σας εδώ",
    "up_url_link": "Μπορείτε επίσης να επικολλήσετε ένα URL",
    "up_url_ph": "Επικολλήστε εδώ τον σύνδεσμο (YouTube κ.λπ.)",
    "up_transcribe": "Μεταγραφή",
    "up_uploading": "Μεταφόρτωση…",
    "unlock_wait_title": "Η πληρωμή ελήφθη — ολοκληρώνουμε τη μεταγραφή σας",
    "unlock_wait_sub": "Μεταγράφουμε το πλήρες κείμενο. Θα εμφανιστεί εδώ μόνο του σε λίγα δευτερόλεπτα.",
    "tt_h1": "Μίλα και μετέτρεψέ το σε κείμενο",
    "tt_sub": "Πατήστε το μικρόφωνο, μιλήστε και λάβετε τη φωνή σας σε κείμενο σε δευτερόλεπτα.",
    "mic_tap": "Πατήστε για να ξεκινήσετε την εγγραφή",
    "mic_start": "Έναρξη μεταγραφής",
    "mic_again": "Εγγραφή ξανά",
    "expired": "Το αρχικό αρχείο έληξε και διαγράφηκε. Μετά τη συνδρομή, ανεβάστε το ξανά για να ολοκληρωθεί η απομαγνητοφώνηση.",
    "it_search": "Εύρεση και αντικατάσταση",
    "it_save": "Αποθήκευση αλλαγών",
    "it_pdf": "Εξαγωγή PDF",
    "it_docx": "Εξαγωγή DOCX",
    "it_txt": "Εξαγωγή TXT",
    "it_srt": "Εξαγωγή SRT",
    "it_ts": "Εμφάνιση χρονικών σημάνσεων",
    "it_translate": "Μετάφραση",
    "it_share": "Κοινοποίηση απομαγνητοφώνησης",
    "it_audio": "Εξαγωγή ήχου",
    "it_rename": "Μετονομασία αρχείου",
    "it_move": "Μετακίνηση",
    "it_delete": "Διαγραφή αρχείου",
    "item_locked": "Ξεκλειδώστε για να χρησιμοποιήσετε αυτή την επιλογή",
    "reupload_title": "Ανεβάστε το πλήρες αρχείο σας",
    "reupload_desc": "Η συνδρομή σας είναι ενεργή. Επειδή το αρχείο ήταν μεγάλο, ανεβάστε το ξανά (ολόκληρο) για να λάβετε την πλήρη απομαγνητοφώνηση.",
    "reupload_btn": "Ανέβασμα πλήρους αρχείου",
    "uploading": "Ανέβασμα και απομαγνητοφώνηση…",
    "eo_title": "Περιμένετε — σας το κάνουμε φθηνότερο",
    "eo_text": "Η απομαγνητοφώνησή σας είναι έτοιμη. Πάρτε την σήμερα για {oferta} αντί για {normal}. {days} ημέρες πρόσβασης και, αν δεν ακυρώσετε, η συνδρομή συνεχίζεται με {monthly}/μήνα.",
    "eo_accept": "Ναι, θέλω την απομαγνητοφώνησή μου για {oferta}",
    "eo_decline": "Όχι, ευχαριστώ",
    "manual_email_q": "Θέλετε email όταν είναι έτοιμη;",
    "manual_email_btn": "Ειδοποίησέ με",
    "manual_email_ok": "Έγινε! Θα σας στείλουμε email μόλις είναι έτοιμη.",
    "acct_title": "Ο λογαριασμός μου",
    "acct_email": "Email",
    "acct_name": "Όνομα",
    "acct_sub": "Συνδρομή",
    "acct_status_none": "Χωρίς συνδρομή",
    "acct_status_trial": "Σε δοκιμαστική περίοδο",
    "acct_status_active": "Ενεργή",
    "acct_status_pastdue": "Εκπρόθεσμη πληρωμή",
    "acct_status_canceled": "Ακυρωμένη",
    "acct_renews": "Ανανεώνεται στις",
    "acct_ends": "Πρόσβαση έως",
    "acct_trans": "Απομαγνητοφωνήσεις",
    "acct_cancel": "Ακύρωση συνδρομής",
    "acct_cancel_confirm": "Σίγουρα θέλετε να ακυρώσετε; Διατηρείτε την πρόσβαση έως το τέλος της περιόδου που έχετε ήδη πληρώσει.",
    "acct_canceled_note": "Η συνδρομή ακυρώθηκε. Διατηρείτε την πρόσβαση έως {date}.",
    "acct_cancel_ok": "Η συνδρομή σας ακυρώθηκε. Διατηρείτε την πρόσβαση έως το τέλος της περιόδου.",
    "acct_see_plans": "Δείτε τα πλάνα",
    "acct_cancel_err": "✗ Δεν ήταν δυνατή η ακύρωση. Γράψτε μας στο {email}.",
    "up_ok": "Το μηνιαίο πλάνο ενεργοποιήθηκε! Έχετε πλέον απεριόριστες απομαγνητοφωνήσεις.",
    "acct_upgrade": "Μετάβαση στο μηνιαίο πλάνο (απεριόριστο)",
    "thanks_title": "Η πληρωμή ολοκληρώθηκε!",
    "thanks_sub": "Η απομαγνητοφώνησή σας ξεκλειδώνεται. Θα σας μεταφέρουμε εκεί σε λίγα δευτερόλεπτα…",
    "thanks_btn": "Δείτε την απομαγνητοφώνησή μου",
    "tt_meta_title": "Ομιλία σε κείμενο — υπαγορεύστε με τη φωνή σας και μετατρέψτε την σε κείμενο online",
    "tt_meta_desc": "Μετατρέψτε τη φωνή σας σε κείμενο αμέσως: πατήστε το μικρόφωνο, μιλήστε και εξαγάγετε την απομαγνητοφώνηση σε TXT, DOCX, PDF ή SRT. Πάνω από 90 γλώσσες, απευθείας στον browser.",
    "mic_recording": "Εγγραφή",
    "mic_stop": "Πατήστε το κουμπί για να ολοκληρώσετε",
    "mic_uploading": "Ανέβασμα και απομαγνητοφώνηση…",
    "mic_denied": "Δεν ήταν δυνατή η πρόσβαση στο μικρόφωνό σας. Επιτρέψτε την πρόσβαση στο μικρόφωνο από τον browser και δοκιμάστε ξανά.",
    "tt_or": "Έχετε ήδη αρχείο ήχου ή βίντεο;",
    "tt_upload": "Ανεβάστε το εδώ",
    "up_err": "Το ανέβασμα απέτυχε. Ελέγξτε τη σύνδεσή σας και δοκιμάστε ξανά.",
    "up_legal_pre": "Ανεβάζοντας αρχείο ή URL αποδέχεστε τους",
    "up_fast_hint": "Γρήγορη απομαγνητοφώνηση με AI",
    "up_langs_hint": "Πάνω από 90 γλώσσες",
    "up_url_hint": "Επικόλληση URL",
    "up_mic_hint": "Εγγραφή με το μικρόφωνο",
    "pr_badge_trial": "Δοκιμή {today}",
    "pr_trial_line": "{today} για τις πρώτες {n} ημέρες, μετά {price}/{per}",
    "pr_err_pay": "⚠️ Δεν ήταν δυνατή η έναρξη της πληρωμής. Δοκιμάστε ξανά σε λίγα λεπτά.",
    "pr_err_config": "⚠️ Αυτό το πλάνο δεν είναι ακόμη διαθέσιμο για πληρωμή. Δοκιμάστε ξανά σύντομα.",
    "per_month": "μήνα",
    "per_year": "έτος",
    "dash_new": "Νέα απομαγνητοφώνηση",
    "dash_mine": "Οι απομαγνητοφωνήσεις μου",
    "dash_empty": "Δεν έχετε ακόμη απομαγνητοφωνήσεις. Ανεβάστε το πρώτο σας αρχείο ήχου ή βίντεο παραπάνω.",
    "th_title": "Τίτλος",
    "th_lang": "Γλώσσα",
    "th_mode": "Λειτουργία",
    "th_status": "Κατάσταση",
    "th_date": "Ημερομηνία",
    "open": "Άνοιγμα →",
    "st_done": "Έτοιμη",
    "st_proc": "Σε επεξεργασία",
    "st_manual": "⏳ Σε εξέλιξη · <24 ώρες",
    "st_queued": "Σε αναμονή",
    "st_err": "Σφάλμα",
    "err_nofile": "Ανεβάστε ένα αρχείο ή επικολλήστε ένα URL.",
    "err_badtype": "Αυτό το αρχείο δεν είναι έγκυρο αρχείο ήχου ή βίντεο. Αποδεκτές μορφές: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
    "err_toobig": "Το αρχείο είναι πολύ μεγάλο.",
    "err_max": "(μέγιστο {max} MB)",
    "err_infected": "Το αρχείο απορρίφθηκε για λόγους ασφαλείας: το antivirus εντόπισε απειλή.",
    "err_limit": "Κάνατε αρκετές προσπάθειες στη σειρά. Περιμένετε λίγο και δοκιμάστε ξανά.",
    "back": "← Πίσω",
    "logout": "Αποσύνδεση",
    "export_label": "Εξαγωγή:",
    "nav_dashboard": "Ο πίνακάς μου",
    "side_dash": "🏠 Οι απομαγνητοφωνήσεις μου",
    "side_new": "➕ Νέα",
    "side_account": "👤 Ο λογαριασμός μου",
    "side_admin": "⚙️ Διαχείριση",
    "ed_saved": "Αποθηκεύτηκε ✓",
    "ed_saving": "Αποθήκευση…",
    "ed_copy": "Αντιγραφή",
    "ed_copied": "Αντιγράφηκε!",
    "err_generic": "Δεν ήταν δυνατή η επεξεργασία του ανεβάσματος."
  }
};
