import { UI_TRANSLATIONS } from "./ui.generated.ts";

/** Textos de UI de la página de resultado y del checkout (localizados). Placeholders {today} {price} {n} {x}. */
export type UIStrings = Record<string, string>;

export const UI_ES: UIStrings = {
  proc_title: "Preparando tu transcripción…",
  proc_sub: "Estamos procesando tu audio para que sea preciso.",
  err: "No se pudo transcribir. Prueba con otro archivo o inténtalo de nuevo.",
  missing: "Te faltan {x} de transcripción",
  unlock_title: "Desbloquea la transcripción",
  pitch: "Esto es solo el comienzo. Desbloquea la transcripción completa, edítala y descárgala en TXT, DOCX, PDF y SRT.",
  cta: "Desbloquear ahora — {today}",
  cta_sub: "{today} los primeros {n} días, luego {price}/mes · Cancela cuando quieras.",
  expired: "El archivo original ha caducado y se ha borrado. Tras suscribirte, vuelve a subirlo para completar la transcripción.",
  sec_edit: "Editar", sec_export: "Exportar", sec_more: "Más",
  it_search: "Buscar y reemplazar", it_save: "Guardar cambios",
  it_pdf: "Descargar PDF", it_docx: "Descargar DOCX", it_txt: "Descargar TXT", it_srt: "Descargar SRT",
  it_ts: "Mostrar marcas de tiempo", it_translate: "Traducir", it_share: "Compartir transcripción",
  it_audio: "Descargar audio", it_rename: "Renombrar archivo", it_move: "Mover", it_delete: "Eliminar archivo",
  item_locked: "Desbloquea para usar esta opción",
  pay_today: "A pagar hoy",
  pay_desc: "{n} días de acceso completo. Después {price}/mes. Cancela cuando quieras.",
  email: "Email", loading_pay: "Cargando pago seguro…", processing: "Procesando…",
  legal_pre: "Al continuar aceptas nuestros", legal_terms: "Términos", legal_sub: "Suscripción y reembolsos", legal_privacy: "Privacidad",
  pay_secure: "Pago seguro con Stripe.", email_invalid: "Introduce un email válido.", pay_error: "No se pudo procesar el pago.",
  reupload_title: "Sube tu archivo completo",
  reupload_desc: "Tu suscripción está activa. Como el archivo era grande, súbelo de nuevo (completo) para obtener la transcripción entera.",
  reupload_btn: "Subir archivo completo", uploading: "Subiendo y transcribiendo…",
  eo_title: "Espera — te la dejamos más barata",
  eo_text: "Tu transcripción ya está lista. Llévatela hoy por {oferta} en vez de {normal}. {days} días de acceso y, si no cancelas, la suscripción sigue a {monthly} al mes.",
  eo_accept: "Sí, quiero mi transcripción por {oferta}", eo_decline: "No, gracias",
  manual_title: "Tu transcripción estará lista en menos de 24 horas",
  manual_desc: "Los vídeos de esta plataforma los procesa nuestro equipo. Aparecerá aquí automáticamente en cuanto esté lista — guarda esta página.",
  manual_email_q: "¿Te avisamos por email cuando esté lista?",
  manual_email_btn: "Avisarme", manual_email_ok: "¡Hecho! Te avisaremos en cuanto esté lista.",
  acct_title: "Mi cuenta", acct_email: "Email", acct_name: "Nombre", acct_sub: "Suscripción",
  acct_status_none: "Sin suscripción", acct_status_trial: "En periodo de prueba", acct_status_active: "Activa",
  acct_status_pastdue: "Pago pendiente", acct_status_canceled: "Cancelada",
  acct_renews: "Se renueva el", acct_ends: "Acceso hasta el", acct_trans: "Transcripciones",
  acct_cancel: "Cancelar suscripción", acct_cancel_confirm: "¿Seguro que quieres cancelar? Mantendrás el acceso hasta el final del periodo ya pagado.",
  acct_canceled_note: "Suscripción cancelada. Mantienes el acceso hasta el {date}.",
  acct_cancel_ok: "Tu suscripción se ha cancelado. Mantienes el acceso hasta el final del periodo.",
  acct_see_plans: "Ver planes",
  quota_title: "El plan de 7 días de prueba solo incluye una transcripción",
  quota_desc: "Si quieres tener transcripciones ilimitadas, activa el plan ahora.",
  quota_cta: "Activar mi plan ahora",
  quota_later: "Quizá más tarde",
  up_ok: "¡Plan mensual activado! Ya tienes transcripciones ilimitadas.",
  acct_upgrade: "Pasar al plan mensual (ilimitado)",
  thanks_title: "¡Pago completado!",
  thanks_sub: "Tu transcripción se está desbloqueando. Te llevamos a ella en unos segundos…",
  thanks_btn: "Ver mi transcripción",
};

export const UI_EN: UIStrings = {
  proc_title: "Preparing your transcription…",
  proc_sub: "We're processing your audio for accuracy.",
  err: "We couldn't transcribe it. Try another file or try again.",
  missing: "You're missing {x} of transcription",
  unlock_title: "Unlock the transcription",
  pitch: "This is just the beginning. Unlock the full transcription, edit it and download it as TXT, DOCX, PDF and SRT.",
  cta: "Unlock now — {today}",
  cta_sub: "{today} for the first {n} days, then {price}/mo · Cancel anytime.",
  expired: "The original file has expired and been deleted. After subscribing, upload it again to complete the transcription.",
  sec_edit: "Edit", sec_export: "Export", sec_more: "More",
  it_search: "Find and replace", it_save: "Save changes",
  it_pdf: "Download PDF", it_docx: "Download DOCX", it_txt: "Download TXT", it_srt: "Download SRT",
  it_ts: "Show timestamps", it_translate: "Translate", it_share: "Share transcription",
  it_audio: "Download audio", it_rename: "Rename file", it_move: "Move", it_delete: "Delete file",
  item_locked: "Unlock to use this option",
  pay_today: "Due today",
  pay_desc: "{n} days of full access. Then {price}/mo. Cancel anytime.",
  email: "Email", loading_pay: "Loading secure payment…", processing: "Processing…",
  legal_pre: "By continuing you agree to our", legal_terms: "Terms", legal_sub: "Subscription & refunds", legal_privacy: "Privacy",
  pay_secure: "Secure payment with Stripe.", email_invalid: "Enter a valid email.", pay_error: "Payment couldn't be processed.",
  reupload_title: "Upload your full file",
  reupload_desc: "Your subscription is active. Since the file was large, upload it again (in full) to get the complete transcription.",
  reupload_btn: "Upload full file", uploading: "Uploading and transcribing…",
  eo_title: "Wait — we'll make it cheaper",
  eo_text: "Your transcription is ready. Get it today for {oferta} instead of {normal}. {days} days of access and, unless you cancel, the subscription continues at {monthly}/mo.",
  eo_accept: "Yes, I want my transcription for {oferta}", eo_decline: "No, thanks",
  manual_title: "Your transcription will be ready within 24 hours",
  manual_desc: "Videos from this platform are processed by our team. It will appear here automatically once it's ready — keep this page.",
  manual_email_q: "Want an email when it's ready?",
  manual_email_btn: "Notify me", manual_email_ok: "Done! We'll email you as soon as it's ready.",
  acct_title: "My account", acct_email: "Email", acct_name: "Name", acct_sub: "Subscription",
  acct_status_none: "No subscription", acct_status_trial: "On trial", acct_status_active: "Active",
  acct_status_pastdue: "Payment past due", acct_status_canceled: "Canceled",
  acct_renews: "Renews on", acct_ends: "Access until", acct_trans: "Transcriptions",
  acct_cancel: "Cancel subscription", acct_cancel_confirm: "Are you sure you want to cancel? You'll keep access until the end of the period you've paid for.",
  acct_canceled_note: "Subscription canceled. You keep access until {date}.",
  acct_cancel_ok: "Your subscription has been canceled. You keep access until the end of the period.",
  acct_see_plans: "See plans",
  quota_title: "The 7-day trial includes only one transcription",
  quota_desc: "If you want unlimited transcriptions, activate the plan now.",
  quota_cta: "Activate my plan now",
  quota_later: "Maybe later",
  up_ok: "Monthly plan activated! You now have unlimited transcriptions.",
  acct_upgrade: "Switch to the monthly plan (unlimited)",
  thanks_title: "Payment complete!",
  thanks_sub: "Your transcription is being unlocked. Taking you there in a few seconds…",
  thanks_btn: "View my transcription",
};

/** Devuelve los textos de UI para un idioma (fallback a inglés). */
export function ui(locale: string): UIStrings {
  if (locale === "es") return UI_ES;
  if (locale === "en") return UI_EN;
  return { ...UI_EN, ...(UI_TRANSLATIONS[locale] || {}) };
}
