import { UI_TRANSLATIONS } from "./ui.generated.ts";

/** Textos de UI de la página de resultado y del checkout (localizados). Placeholders {today} {price} {n} {x}. */
export type UIStrings = Record<string, string>;

export const UI_ES: UIStrings = {
  proc_title: "Preparando tu transcripción…",
  proc_sub: "Estamos procesando tu audio para que sea preciso.",
  err: "No se pudo transcribir. Prueba con otro archivo o inténtalo de nuevo.",
  missing: "Te faltan {x} de transcripción",
  unlock_title: "Desbloquea la transcripción",
  pitch: "Esto es solo el comienzo. Desbloquea la transcripción completa, edítala y expórtala en TXT, DOCX, PDF y SRT.",
  cta: "Desbloquear ahora — {today}",
  cta_sub: "{today} los primeros {n} días, luego {price}/mes · Cancela cuando quieras.",
  expired: "El archivo original ha caducado y se ha borrado. Tras suscribirte, vuelve a subirlo para completar la transcripción.",
  sec_edit: "Editar", sec_export: "Exportar", sec_more: "Más",
  it_search: "Buscar y reemplazar", it_save: "Guardar cambios",
  it_pdf: "Descargar PDF", it_docx: "Descargar DOCX", it_txt: "Descargar TXT", it_srt: "Descargar SRT",
  it_ts: "Mostrar marcas de tiempo", it_translate: "Traducir", it_share: "Compartir transcripción",
  it_audio: "Descargar audio", it_rename: "Renombrar archivo", it_move: "Mover", it_delete: "Eliminar archivo",
  item_locked: "Desbloquea para usar esta opción",
  pay_today: "A pagar hoy",
  pay_desc: "{n} días de acceso completo. Después {price}/mes. Cancela cuando quieras.",
  email: "Email", loading_pay: "Cargando pago seguro…", processing: "Procesando…",
  legal_pre: "Al continuar aceptas nuestros", legal_terms: "Términos", legal_sub: "Suscripción y reembolsos", legal_privacy: "Privacidad",
  pay_secure: "Pago seguro con Stripe.", email_invalid: "Introduce un email válido.", pay_error: "No se pudo procesar el pago.",
  reupload_title: "Sube tu archivo completo",
  reupload_desc: "Tu suscripción está activa. Como el archivo era grande, súbelo de nuevo (completo) para obtener la transcripción entera.",
  reupload_btn: "Subir archivo completo", uploading: "Subiendo y transcribiendo…",
  eo_title: "Espera — te la dejamos más barata",
  eo_text: "Tu transcripción ya está lista. Llévatela hoy por {oferta} en vez de {normal}. {days} días de acceso y, si no cancelas, la suscripción sigue a {monthly} al mes.",
  eo_accept: "Sí, quiero mi transcripción por {oferta}", eo_decline: "No, gracias",
  manual_unlock_title: "Desbloquea la transcripción de tu vídeo",
  manual_unlock_desc: "Obtén el texto completo de este vídeo, editable y listo para exportar en TXT, DOCX, PDF y SRT.",
  manual_title: "Tu transcripción estará lista en menos de 24 horas",
  manual_desc: "Los vídeos de esta plataforma los procesa nuestro equipo. Aparecerá aquí automáticamente en cuanto esté lista — guarda esta página.",
  manual_email_q: "¿Te avisamos por email cuando esté lista?",
  manual_email_btn: "Avisarme", manual_email_ok: "¡Hecho! Te avisaremos en cuanto esté lista.",
  acct_title: "Mi cuenta", acct_email: "Email", acct_name: "Nombre", acct_sub: "Suscripción",
  acct_status_none: "Sin suscripción", acct_status_trial: "En periodo de prueba", acct_status_active: "Activa",
  acct_status_pastdue: "Pago pendiente", acct_status_canceled: "Cancelada",
  acct_renews: "Se renueva el", acct_ends: "Acceso hasta el", acct_trans: "Transcripciones",
  acct_cancel: "Cancelar suscripción", acct_cancel_confirm: "¿Seguro que quieres cancelar? Mantendrás el acceso hasta el final del periodo ya pagado.",
  acct_canceled_note: "Suscripción cancelada. Mantienes el acceso hasta el {date}.",
  acct_cancel_ok: "Tu suscripción se ha cancelado. Mantienes el acceso hasta el final del periodo.",
  acct_see_plans: "Ver planes",
  quota_title: "El plan de 7 días de prueba solo incluye una transcripción",
  quota_desc: "Si quieres tener transcripciones ilimitadas, activa el plan ahora.",
  quota_cta: "Activar mi plan ahora",
  quota_later: "Quizá más tarde",
  up_ok: "¡Plan mensual activado! Ya tienes transcripciones ilimitadas.",
  acct_upgrade: "Pasar al plan mensual (ilimitado)",
  thanks_title: "¡Pago completado!",
  thanks_sub: "Tu transcripción se está desbloqueando. Te llevamos a ella en unos segundos…",
  thanks_btn: "Ver mi transcripción",
  tt_h1: "Habla y conviértelo en texto",
  tt_sub: "Pulsa el micrófono, habla, y obtén tu voz transcrita a texto en segundos. Sin instalar nada.",
  mic_tap: "Pulsa para empezar a grabar",
  mic_recording: "Grabando", mic_stop: "Pulsa el botón para terminar",
  mic_again: "Grabar de nuevo", mic_start: "Iniciar transcripción",
  mic_uploading: "Subiendo y transcribiendo…",
  mic_denied: "No pudimos acceder al micrófono. Permite el acceso en tu navegador e inténtalo de nuevo.",
  tt_or: "¿Ya tienes un archivo de audio o vídeo?", tt_upload: "Súbelo aquí",
  up_drag: "o arrastra y suelta tu archivo aquí",
  up_url_link: "También puedes pegar una URL",
  up_url_ph: "Pega aquí el enlace (YouTube, etc.)",
  up_transcribe: "Transcribir", up_uploading: "Subiendo…",
  up_err: "No se pudo subir. Revisa tu conexión e inténtalo de nuevo.",
  up_legal_pre: "Al subir un archivo o URL aceptas nuestros",
  unlock_wait_title: "Pago recibido — completando tu transcripción",
  unlock_wait_sub: "Estamos transcribiendo el texto completo. En unos segundos aparecerá aquí solo.",
  up_fast_hint: "Transcripción IA rápida", up_langs_hint: "Más de 90 idiomas",
  up_url_hint: "Pegar una URL", up_mic_hint: "Graba con tu micrófono",
  // Precios / panel / cuenta / home (antes literales en los componentes)
  pr_badge_trial: "Prueba {today}", pr_trial_line: "{today} los primeros {n} días, luego {price}/{per}",
  pr_err_pay: "⚠️ No se pudo iniciar el pago. Inténtalo de nuevo en unos minutos.", pr_err_config: "⚠️ Este plan aún no está disponible para pago. Vuelve a intentarlo pronto.",
  per_month: "mes", per_year: "año",
  dash_new: "Nueva transcripción", dash_mine: "Mis transcripciones", dash_empty: "Aún no tienes transcripciones. Sube tu primer audio o vídeo arriba.",
  th_title: "Título", th_lang: "Idioma", th_mode: "Modo", th_status: "Estado", th_date: "Fecha", open: "Abrir →",
  st_done: "Lista", st_proc: "Procesando", st_manual: "⏳ En proceso · <24h", st_queued: "En cola", st_err: "Error",
  err_nofile: "Sube un archivo o pega una URL.", err_badtype: "Ese archivo no es un audio o vídeo válido. Formatos aceptados: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
  err_toobig: "El archivo es demasiado grande.", err_max: "(máximo {max} MB)", err_infected: "El archivo se ha rechazado por seguridad: el antivirus detectó una amenaza.",
  err_limit: "Has hecho varias pruebas seguidas. Espera un momento e inténtalo de nuevo.",
  acct_cancel_err: "✗ No se pudo cancelar. Escríbenos a {email}.",
  back: "← Volver", logout: "Cerrar sesión", export_label: "Exportar:", nav_dashboard: "Mi panel", side_dash: "🏠 Mis transcripciones", side_new: "➕ Nueva", side_account: "👤 Mi cuenta", side_admin: "⚙️ Administración", ed_saved: "Guardado ✓", ed_saving: "Guardando…", ed_copy: "Copiar", ed_copied: "¡Copiado!", err_generic: "No se pudo procesar la subida.",
  tt_meta_title: "Hablar a Texto — Dicta con tu voz y conviértela en texto", tt_meta_desc: "Convierte tu voz en texto al instante: pulsa el micrófono, habla y exporta la transcripción en TXT, DOCX, PDF o SRT. Más de 90 idiomas, funciona en el navegador.",
};

export const UI_EN: UIStrings = {
  proc_title: "Preparing your transcription…",
  proc_sub: "We're processing your audio for accuracy.",
  err: "We couldn't transcribe it. Try another file or try again.",
  missing: "You're missing {x} of transcription",
  unlock_title: "Unlock the transcription",
  pitch: "This is just the beginning. Unlock the full transcription, edit it and export it as TXT, DOCX, PDF and SRT.",
  cta: "Unlock now — {today}",
  cta_sub: "{today} for the first {n} days, then {price}/mo · Cancel anytime.",
  expired: "The original file has expired and been deleted. After subscribing, upload it again to complete the transcription.",
  sec_edit: "Edit", sec_export: "Export", sec_more: "More",
  it_search: "Find and replace", it_save: "Save changes",
  it_pdf: "Download PDF", it_docx: "Download DOCX", it_txt: "Download TXT", it_srt: "Download SRT",
  it_ts: "Show timestamps", it_translate: "Translate", it_share: "Share transcription",
  it_audio: "Download audio", it_rename: "Rename file", it_move: "Move", it_delete: "Delete file",
  item_locked: "Unlock to use this option",
  pay_today: "Due today",
  pay_desc: "{n} days of full access. Then {price}/mo. Cancel anytime.",
  email: "Email", loading_pay: "Loading secure payment…", processing: "Processing…",
  legal_pre: "By continuing you agree to our", legal_terms: "Terms", legal_sub: "Subscription & refunds", legal_privacy: "Privacy",
  pay_secure: "Secure payment with Stripe.", email_invalid: "Enter a valid email.", pay_error: "Payment couldn't be processed.",
  reupload_title: "Upload your full file",
  reupload_desc: "Your subscription is active. Since the file was large, upload it again (in full) to get the complete transcription.",
  reupload_btn: "Upload full file", uploading: "Uploading and transcribing…",
  eo_title: "Wait — we'll make it cheaper",
  eo_text: "Your transcription is ready. Get it today for {oferta} instead of {normal}. {days} days of access and, unless you cancel, the subscription continues at {monthly}/mo.",
  eo_accept: "Yes, I want my transcription for {oferta}", eo_decline: "No, thanks",
  manual_unlock_title: "Unlock your video's transcription",
  manual_unlock_desc: "Get the full text of this video, editable and ready to export as TXT, DOCX, PDF and SRT.",
  manual_title: "Your transcription will be ready within 24 hours",
  manual_desc: "Videos from this platform are processed by our team. It will appear here automatically once it's ready — keep this page.",
  manual_email_q: "Want an email when it's ready?",
  manual_email_btn: "Notify me", manual_email_ok: "Done! We'll email you as soon as it's ready.",
  acct_title: "My account", acct_email: "Email", acct_name: "Name", acct_sub: "Subscription",
  acct_status_none: "No subscription", acct_status_trial: "On trial", acct_status_active: "Active",
  acct_status_pastdue: "Payment past due", acct_status_canceled: "Canceled",
  acct_renews: "Renews on", acct_ends: "Access until", acct_trans: "Transcriptions",
  acct_cancel: "Cancel subscription", acct_cancel_confirm: "Are you sure you want to cancel? You'll keep access until the end of the period you've paid for.",
  acct_canceled_note: "Subscription canceled. You keep access until {date}.",
  acct_cancel_ok: "Your subscription has been canceled. You keep access until the end of the period.",
  acct_see_plans: "See plans",
  quota_title: "The 7-day trial includes only one transcription",
  quota_desc: "If you want unlimited transcriptions, activate the plan now.",
  quota_cta: "Activate my plan now",
  quota_later: "Maybe later",
  up_ok: "Monthly plan activated! You now have unlimited transcriptions.",
  acct_upgrade: "Switch to the monthly plan (unlimited)",
  thanks_title: "Payment complete!",
  thanks_sub: "Your transcription is being unlocked. Taking you there in a few seconds…",
  thanks_btn: "View my transcription",
  tt_h1: "Talk to Text — speak, and get it in writing",
  tt_sub: "Tap the mic, start talking, and get your voice converted to text in seconds. Nothing to install.",
  mic_tap: "Tap to start recording",
  mic_recording: "Recording", mic_stop: "Tap the button to finish",
  mic_again: "Record again", mic_start: "Start transcription",
  mic_uploading: "Uploading & transcribing…",
  mic_denied: "We couldn't access your microphone. Allow mic access in your browser and try again.",
  tt_or: "Already have an audio or video file?", tt_upload: "Upload it here",
  up_drag: "or drag & drop your file here",
  up_url_link: "You can also paste a URL",
  up_url_ph: "Paste your link here (YouTube, etc.)",
  up_transcribe: "Transcribe", up_uploading: "Uploading…",
  up_err: "Upload failed. Check your connection and try again.",
  up_legal_pre: "By uploading a file or URL you agree to our",
  unlock_wait_title: "Payment received — finishing your transcription",
  unlock_wait_sub: "We're transcribing the full text. It will appear here by itself in a few seconds.",
  up_fast_hint: "Fast AI transcription", up_langs_hint: "90+ languages",
  up_url_hint: "Paste a URL", up_mic_hint: "Record with your microphone",
  // Pricing / dashboard / account / home (formerly hard-coded in components)
  pr_badge_trial: "Trial {today}", pr_trial_line: "{today} for the first {n} days, then {price}/{per}",
  pr_err_pay: "⚠️ We couldn't start the payment. Please try again in a few minutes.", pr_err_config: "⚠️ This plan isn't available for payment yet. Please try again soon.",
  per_month: "month", per_year: "year",
  dash_new: "New transcription", dash_mine: "My transcriptions", dash_empty: "You don't have any transcriptions yet. Upload your first audio or video above.",
  th_title: "Title", th_lang: "Language", th_mode: "Mode", th_status: "Status", th_date: "Date", open: "Open →",
  st_done: "Ready", st_proc: "Processing", st_manual: "⏳ In progress · <24h", st_queued: "Queued", st_err: "Error",
  err_nofile: "Upload a file or paste a URL.", err_badtype: "That file isn't a valid audio or video. Accepted formats: MP3, WAV, M4A, AAC, OGG, MP4, MOV, MKV, WEBM…",
  err_toobig: "The file is too large.", err_max: "(max {max} MB)", err_infected: "The file was rejected for security reasons: the antivirus detected a threat.",
  err_limit: "You've made several attempts in a row. Wait a moment and try again.",
  acct_cancel_err: "✗ We couldn't cancel. Write to us at {email}.",
  back: "← Back", logout: "Log out", export_label: "Export:", nav_dashboard: "My dashboard", side_dash: "🏠 My transcriptions", side_new: "➕ New", side_account: "👤 My account", side_admin: "⚙️ Admin", ed_saved: "Saved ✓", ed_saving: "Saving…", ed_copy: "Copy", ed_copied: "Copied!", err_generic: "The upload couldn't be processed.",
  tt_meta_title: "Talk to Text — Speak & Convert Your Voice to Text Online", tt_meta_desc: "Talk to text online: tap the mic, speak, and get an instant transcription. Export as TXT, DOCX, PDF or SRT. 90+ languages, works in your browser.",
};

/** Devuelve los textos de UI para un idioma (fallback a inglés). */
export function ui(locale: string): UIStrings {
  if (locale === "es") return UI_ES;
  if (locale === "en") return UI_EN;
  return { ...UI_EN, ...(UI_TRANSLATIONS[locale] || {}) };
}

/** Sustituye {clave} por su valor. */
export function fmt(str: string | undefined, vars: Record<string, string | number>): string {
  return Object.keys(vars).reduce((a, k) => a.replaceAll(`{${k}}`, String(vars[k])), str ?? "");
}
